/*
Domain: Typed observation inspection
Owns: Generated expected runtime, metadata, descriptor, weight, and fanout evidence.
Excludes: Live chain evidence, observation state, and estimate projection.
Zone: Generated observation domain evidence; regenerate through the owning script.
*/
export const DEOS_OBSERVATION_RUNTIME_EVIDENCE = {
  runtime: {
    specName: 'deos-runtime',
    implName: 'deos-runtime',
    authoringVersion: 1,
    specVersion: 1,
    implVersion: 1,
    systemVersion: 3,
    transactionVersion: 1,
  },
  runtimeCodeHash:
    '0x16f95188d3ce591c43ea500bbb14e1a889051421625c39cd5144fb9f8432dcf9',
  metadataHash:
    '0x63a1cce08329da68dafba9cd377e8f3b750641ed96d724355ec3a6f22f1e50fd',
  metadataSha256:
    '75868ea75fd85e7b79db12650a7407e89e249f5564b2157d55ac46cd26cb5d12',
  descriptorIdentity: '0.1.0-autogenerated.17618355743500111702',
  weightIdentity:
    'sha256:9ce37ade391a29d4f60779f1887ad242dfeb4919d25cf0047ffba85d18f33901',
  certifiedPublishers: ['DEOS Oracle::OnObservationChanged'],
  fanout: {
    configuredServiceUnitsPerBlock: 64,
    fanoutWeightLimit: {
      refTime: 400000000000,
      proofSize: 1000000,
    },
    fanoutBaseWeight: {
      refTime: 56775000,
      proofSize: 1629,
    },
    serviceUnitWeight: {
      refTime: 45884158000,
      proofSize: 304734,
    },
    maxServiceUnitsPerBlock: 3,
    maxActiveDirtyFeeds: 10000,
    maxSubscriberPagesPerFeed: 157,
  },
} as const;
