/*
Domain: Typed observation inspection
Owns: Generated expected runtime, metadata, descriptor, weight, and fanout evidence.
Excludes: Live chain evidence, observation state, and estimate projection.
Zone: Generated observation domain evidence; regenerate through the owning script.
*/
export const DEOS_OBSERVATION_RUNTIME_EVIDENCE = {
  runtime: {
    specName: 'deos-runtime',
    implName: 'deos-runtime',
    authoringVersion: 1,
    specVersion: 1,
    implVersion: 1,
    systemVersion: 3,
    transactionVersion: 1,
  },
  runtimeCodeHash:
    '0x94eed043bcb6f429c7165bcdf3d5212fd63a9da5a3e47ef78c989ab5bba0a068',
  metadataHash:
    '0xcc9ff99cfdc0b712820ad8f27dbc3891f6966ddc7b5ce14d7d0bccf6f4157e8e',
  metadataSha256:
    'cfabdcc97265e543fd6d774b8d9bf89cd12033fefd742d9cbb6ba9b62b6a9bfd',
  descriptorIdentity: '0.1.0-autogenerated.8659000061053874806',
  weightIdentity:
    'sha256:552c4564b55ff02ff7b0235dcb79f520fb0075d05e8a2fbdaf85f0ef7d8ae277',
  certifiedPublishers: ['DEOS Oracle::OnObservationChanged'],
  fanout: {
    configuredServiceUnitsPerBlock: 64,
    fanoutWeightLimit: {
      refTime: 400000000000,
      proofSize: 1000000,
    },
    fanoutBaseWeight: {
      refTime: 31566000,
      proofSize: 1543,
    },
    serviceUnitWeight: {
      refTime: 12127164000,
      proofSize: 166430,
    },
    maxServiceUnitsPerBlock: 5,
    maxActiveDirtyFeeds: 40000,
    maxSubscriberPagesPerFeed: 157,
  },
} as const;
