/*
Domain: Typed observation inspection
Owns: Generated expected runtime, metadata, descriptor, weight, and fanout evidence.
Excludes: Live chain evidence, observation state, and estimate projection.
Zone: Generated observation domain evidence; regenerate through the owning script.
*/
export const DEOS_OBSERVATION_RUNTIME_EVIDENCE = {
  runtime: {
    specName: 'deos-runtime',
    implName: 'deos-runtime',
    authoringVersion: 1,
    specVersion: 1,
    implVersion: 1,
    systemVersion: 3,
    transactionVersion: 1,
  },
  runtimeCodeHash:
    '0x4107df9ac3820be5a4f3799884fc33259af10871d2df9d22df0885d96b21eb43',
  metadataHash:
    '0x89918fe545596de2017c4ea300ff442ed883a02c618c67c04a3be34291bb4919',
  metadataSha256:
    '27984891721c42acbce79d4e458e9b40dd6b9a046228438a072f4f2c1bd0f74e',
  descriptorIdentity: '0.1.0-autogenerated.16302145885248040146',
  weightIdentity:
    'sha256:ac206ec06b3f2c2789da23540ca1ae87d343c8d2196f77b1c12c43569c0d3b9e',
  certifiedPublishers: ['DEOS Oracle::OnObservationChanged'],
  fanout: {
    configuredServiceUnitsPerBlock: 64,
    fanoutWeightLimit: {
      refTime: 400000000000,
      proofSize: 1000000,
    },
    fanoutBaseWeight: {
      refTime: 56285000,
      proofSize: 1629,
    },
    serviceUnitWeight: {
      refTime: 36276713000,
      proofSize: 304734,
    },
    maxServiceUnitsPerBlock: 3,
    maxActiveDirtyFeeds: 10000,
    maxSubscriberPagesPerFeed: 157,
  },
} as const;
