/*
Domain: Wiki presentation metadata
Owns: Semantic Lucide icon selection for wiki page identities.
Excludes: Wiki navigation order, localized content, page generation, and generic icon rendering.
Zone: Wiki presentation helper; consumed by WikiWidget without changing generated wiki metadata.
*/
import {
  Activity,
  BadgeCheck,
  Binary,
  BookOpen,
  BookOpenText,
  Bot,
  Boxes,
  CircleQuestionMark,
  Coins,
  Columns3,
  Compass,
  Container,
  Cpu,
  Dices,
  FileQuestionMark,
  FileText,
  FingerprintPattern,
  FolderTree,
  Footprints,
  Gauge,
  GitBranch,
  Hammer,
  Handshake,
  HeartHandshake,
  Landmark,
  Layers2,
  ListChecks,
  Map,
  Milestone,
  Monitor,
  Orbit,
  RadioTower,
  Repeat2,
  Route,
  Scale,
  ShieldAlert,
  Sigma,
  Terminal,
  Timer,
  TrendingUp,
  UserRoundCog,
  UsersRound,
  Vote,
  WavesHorizontal,
  Waypoints,
} from '@lucide/svelte';
import type { Component } from 'svelte';

const WIKI_PAGE_ICONS: Record<string, Component<any>> = {
  'start-here': Compass,
  'deos-in-60-seconds': Timer,
  'partner-pitch': Handshake,
  'executive-summary': FileText,
  'deos-framework': Boxes,
  'first-steps': Footprints,
  'core-terms': BookOpenText,
  'reading-paths': Route,
  'newcomer-faq': CircleQuestionMark,
  'tmctol-standard': Orbit,
  'token-driven-automation': Bot,
  'read-model-split': Columns3,
  'governance-domains': Landmark,
  'generated-wiki': BookOpen,
  'domain-map': Map,
  'end-to-end-flows': Waypoints,
  'token-surfaces': Coins,
  'builder-economy': Hammer,
  'economic-thresholds': Gauge,
  'parachain-context': RadioTower,
  'tol-bucket-scenarios': Container,
  'invariant-map': ShieldAlert,
  'economic-claim-levels': ListChecks,
  'aaa-system': Cpu,
  'aa-actor': UserRoundCog,
  'axial-router': Milestone,
  'token-minting-curve': TrendingUp,
  'governance-overview': Vote,
  'asset-identity': FingerprintPattern,
  'randomness-strategy': Dices,
  'runtime-patterns': Binary,
  'routing-and-minting-loop': Repeat2,
  'staking-pools': WavesHorizontal,
  'reference-client': Monitor,
  'repository-structure': FolderTree,
  'tech-stack': Layers2,
  'tmctol-formulas': Sigma,
  'scripts-layer': Terminal,
  'forking-deos': GitBranch,
  'agent-coordination': UsersRound,
  'three-layer-validation': BadgeCheck,
  status: Activity,
  'physics-vs-politics': Scale,
  contributing: HeartHandshake,
};

export function iconForWikiPage(pageId: string): Component<any> {
  return WIKI_PAGE_ICONS[pageId] ?? FileQuestionMark;
}
