export {
  ACTORS_MAX_CONTRACT_STEPS,
  ACTORS_MAX_EXECUTION_DELAY_BLOCKS,
  ACTORS_MAX_OPENING_PREDICATE_RESULTS,
  ACTORS_MAX_OPENING_SNAPSHOT_ENTRIES,
  ACTORS_MAX_OWNER_SLOTS,
  ACTORS_MAX_PRECONDITION_CLAUSES,
  ACTORS_MAX_PREDICATES_PER_CLAUSE,
  ACTORS_MAX_PREDICATES_PER_STEP,
  ACTORS_MAX_RETRY_ATTEMPTS,
} from './actors-protocol-bounds.generated.ts';
