/*
Domain: Certified AddressEvent ingress
Owns: Generated expected certified-producer inventory and typed-boundary evidence.
Excludes: Live chain evidence, observation state, and estimate projection.
Zone: Generated ingress domain evidence; regenerate through the owning script.
*/
export const DEOS_INGRESS_RUNTIME_EVIDENCE = {
  runtime: {
    specName: 'deos-runtime',
    implName: 'deos-runtime',
    authoringVersion: 1,
    specVersion: 1,
    implVersion: 1,
    systemVersion: 3,
    transactionVersion: 1,
  },
  inventorySha256:
    'e92869720bad326c9400f73e59b12d95fccfb3511366bb399e147e1c13654fb1',
  certifiedProducers: [
    {
      id: 'AddressEventIngressExtension::signed_transfer',
      protocol: 'BlockAtomicPostDispatch',
      creditedSurface: 'Recipient sovereign',
      sourceProvenance: 'Signer / Signed',
      preflightOwner: 'TransactionExtension::prepare',
      consequenceOwner: 'TransactionExtension::post_dispatch_details',
      rollbackOwner: 'Block author/import state transaction',
      weightOwner: 'transaction_extension_ingress_base/_notify',
    },
    {
      id: 'AddressEventIngressExtension::transfer_all',
      protocol: 'BlockAtomicPostDispatch',
      creditedSurface: 'Recipient sovereign',
      sourceProvenance: 'Signer / Signed, actual recipient delta',
      preflightOwner: 'TransactionExtension::prepare',
      consequenceOwner: 'TransactionExtension::post_dispatch_details',
      rollbackOwner: 'Block author/import state transaction',
      weightOwner: 'transaction_extension_ingress_base/_notify',
    },
    {
      id: 'AddressEventIngressExtension::privileged_or_delegated',
      protocol: 'BlockAtomicPostDispatch',
      creditedSurface: 'Recipient sovereign',
      sourceProvenance: 'Source-less / none',
      preflightOwner: 'TransactionExtension::prepare_dynamic_producer',
      consequenceOwner: 'TransactionExtension::post_dispatch_details',
      rollbackOwner: 'Block author/import state transaction',
      weightOwner: 'transaction_extension_ingress_base/_notify',
    },
    {
      id: 'TmctolAssetOps::transfer',
      protocol: 'PostMovementNotify',
      creditedSurface: 'Task `to` sovereign',
      sourceProvenance: 'Sender / InternalProtocol',
      preflightOwner: 'TmctolAssetOps::transfer preflight',
      consequenceOwner: 'RuntimeAddressEventIngress::on_internal_inbound',
      rollbackOwner: 'Asset ops storage transaction',
      weightOwner: 'task_transfer/task_split_transfer generated weights',
    },
    {
      id: 'TmctolAssetOps::mint',
      protocol: 'PostMovementNotify',
      creditedSurface: 'Task `to` sovereign',
      sourceProvenance: 'Source-less / none',
      preflightOwner: 'TmctolAssetOps::mint preflight',
      consequenceOwner: 'RuntimeAddressEventIngress::on_inbound_without_source',
      rollbackOwner: 'Asset ops storage transaction',
      weightOwner: 'task_mint generated weight',
    },
    {
      id: 'TmctolMintDistributionIngress',
      protocol: 'PostMovementNotify',
      creditedSurface: 'Collateral/minted recipients',
      sourceProvenance: 'Mint source / InternalProtocol',
      preflightOwner: 'before_collateral_transfer/before_sink_mint',
      consequenceOwner: 'after_distribution',
      rollbackOwner: 'TMC distribution transaction',
      weightOwner: 'TMC distribution generated weights',
    },
    {
      id: 'DeosRouter::route_fee',
      protocol: 'PostMovementNotify',
      creditedSurface: 'Burn Actor sovereign',
      sourceProvenance: 'Fee payer / InternalProtocol',
      preflightOwner: 'FeeManagerImpl::route_fee preflight',
      consequenceOwner: 'FeeManagerImpl::route_fee notify',
      rollbackOwner: 'Router fee transaction',
      weightOwner: 'Router fee routing generated weights',
    },
    {
      id: 'XCM asset deposit',
      protocol: 'XcmTransactionalPrecommit',
      creditedSurface: 'Recipient sovereign',
      sourceProvenance: 'XCM origin / Xcm',
      preflightOwner: 'ActorAwareAssetTransactor::preflight_ingress',
      consequenceOwner: 'ActorAwareAssetTransactor::precommit_ingress',
      rollbackOwner: 'ActorAwareAssetTransactor storage transaction',
      weightOwner: 'One-asset deposit generated weight',
    },
    {
      id: 'XCM deposit without origin',
      protocol: 'XcmTransactionalPrecommit',
      creditedSurface: 'Recipient sovereign',
      sourceProvenance: 'Source-less / none',
      preflightOwner: 'ActorAwareAssetTransactor::preflight_ingress',
      consequenceOwner: 'ActorAwareAssetTransactor::precommit_ingress',
      rollbackOwner: 'ActorAwareAssetTransactor storage transaction',
      weightOwner: 'One-asset deposit generated weight',
    },
  ],
  boundary: {
    typedTrait: 'pallet_deos_actors::AddressEventIngress',
    adapter: 'RuntimeAddressEventIngress',
    extension: 'AddressEventIngressExtension',
    helperFiles: [
      'actor_config.rs',
      'address_event_ingress.rs',
      'deos_router_config.rs',
      'tmc_config.rs',
      'xcm_config.rs',
    ],
  },
} as const;
