/*
Domain: AAA generated semantic manifest
Owns: Versioned generated-manifest validation, exhaustive task/amount lookup, and typed semantic transport.
Excludes: Runtime execution, artifact decoding, weight calculation, and task-semantic reconstruction.
Zone: Automation domain contract; generated by the package-owned Rust semantic classifier.
*/
import manifestJson from './aaa-semantic-manifest.json' with { type: 'json' };
import type { AaaAmountName, AaaTaskName } from './analysis.ts';

const TASK_NAMES = [
  'Transfer',
  'SplitTransfer',
  'SwapExactIn',
  'SwapExactOut',
  'AddLiquidity',
  'RemoveLiquidity',
  'Burn',
  'Mint',
  'Stake',
  'DonateLiquidity',
  'Unstake',
  'StopCycle',
] as const satisfies readonly AaaTaskName[];

const AMOUNT_NAMES = [
  'Fixed',
  'PercentageOfCurrent',
  'PercentageOfTrigger',
  'PercentageOfLastFunding',
  'AllBalance',
] as const satisfies readonly AaaAmountName[];

export type AaaSemanticRecipient =
  | { kind: 'ActorSovereign' }
  | { kind: 'Explicit'; path: string }
  | { kind: 'AdapterDerived' };

export type AaaSemanticTask = {
  task: AaaTaskName;
  requiredAdapter:
    | 'None'
    | 'AssetOps'
    | 'DexOps'
    | 'StakingOps'
    | 'LiquidityDonationOps';
  assetsRead: string[];
  assetsWritten: string[];
  readsAdapterDerivedAssets: boolean;
  writesAdapterDerivedAssets: boolean;
  recipients: AaaSemanticRecipient[];
  effects: Array<
    | 'Transfer'
    | 'SupplyBurn'
    | 'SupplyMint'
    | 'LiquidityMutation'
    | 'StakingMutation'
  >;
  availability: 'UserAndSystem' | 'SystemOnly';
  committedNonCompensatedEffects: boolean;
  successfulControl: 'Advance' | 'CompleteCycle';
  weightOwner: string;
  boundedInternalAlgorithm:
    | 'None'
    | 'PalletSplitFanout'
    | 'RuntimeAdapterContract';
  amountSurfaces: Array<{ role: string; path: string }>;
};

export type AaaSemanticAmountResolution = {
  resolution: AaaAmountName;
  dataDependencies: Array<
    | 'ArtifactValue'
    | 'CurrentBalanceOrShares'
    | 'TriggerSnapshot'
    | 'LastFundingSnapshot'
    | 'TaskPolicyCapacity'
  >;
  minimumBalanceDependency: 'None' | 'TaskPolicy';
  feeReserveDependency: 'None' | 'TaskPolicy';
  valueObservationWindow:
    | 'ArtifactTime'
    | 'LogicalRunStart'
    | 'StepAttemptTime';
  retryObservation: 'ReobserveLiveValue' | 'ReuseFrozenValueWithLiveCapacity';
};

export type AaaSemanticManifest = {
  format: 'deos.aaa.semantic-manifest';
  formatVersion: 1;
  tasks: AaaSemanticTask[];
  amountResolutions: AaaSemanticAmountResolution[];
};

function record(value: unknown, label: string): Record<string, unknown> {
  if (value == null || Array.isArray(value) || typeof value !== 'object') {
    throw new Error(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function names(value: unknown, label: string) {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array`);
  return value.map((entry, index) => {
    const projected = record(entry, `${label}[${index}]`);
    if (typeof projected.task === 'string') return projected.task;
    if (typeof projected.resolution === 'string') return projected.resolution;
    throw new Error(`${label}[${index}] has no semantic identity`);
  });
}

function requireExactNames(
  actual: string[],
  expected: readonly string[],
  label: string,
) {
  if (
    actual.length !== expected.length ||
    actual.some((name, index) => name !== expected[index])
  ) {
    throw new Error(
      `${label} variants are unknown, missing, duplicated, or reordered`,
    );
  }
}

export function parseAaaSemanticManifest(value: unknown): AaaSemanticManifest {
  const projected = record(value, 'AAA semantic manifest');
  if (projected.format !== 'deos.aaa.semantic-manifest') {
    throw new Error('Unsupported AAA semantic manifest format');
  }
  if (projected.formatVersion !== 1) {
    throw new Error('Unsupported AAA semantic manifest version');
  }
  requireExactNames(names(projected.tasks, 'tasks'), TASK_NAMES, 'Task');
  requireExactNames(
    names(projected.amountResolutions, 'amountResolutions'),
    AMOUNT_NAMES,
    'AmountResolution',
  );
  return projected as AaaSemanticManifest;
}

export const AAA_SEMANTIC_MANIFEST = parseAaaSemanticManifest(manifestJson);

const TASKS = new Map(
  AAA_SEMANTIC_MANIFEST.tasks.map((task) => [task.task, task]),
);
const AMOUNTS = new Map(
  AAA_SEMANTIC_MANIFEST.amountResolutions.map((amount) => [
    amount.resolution,
    amount,
  ]),
);

export function aaaTaskSemantics(task: string): AaaSemanticTask {
  const semantics = TASKS.get(task as AaaTaskName);
  if (semantics == null) throw new Error(`Unsupported Task variant: ${task}`);
  return semantics;
}

export function aaaAmountSemantics(
  resolution: string,
): AaaSemanticAmountResolution {
  const semantics = AMOUNTS.get(resolution as AaaAmountName);
  if (semantics == null) {
    throw new Error(`Unsupported AmountResolution variant: ${resolution}`);
  }
  return semantics;
}
