/*
Domain: Actors generated semantic manifest
Owns: Versioned generated-manifest validation, exhaustive task/amount lookup, and typed semantic transport.
Excludes: Runtime execution, artifact decoding, weight calculation, and task-semantic reconstruction.
Zone: Automation domain contract; generated by the package-owned Rust semantic classifier.
*/
import manifestJson from './actors-semantic-manifest.json' with { type: 'json' };

export type ActorTaskName =
  | 'Transfer'
  | 'SplitTransfer'
  | 'SwapIn'
  | 'SwapOut'
  | 'AddLiquidity'
  | 'RemoveLiquidity'
  | 'Burn'
  | 'Mint'
  | 'Stake'
  | 'DonateLiquidity'
  | 'Unstake'
  | 'StopCycle';

export type ActorPredicateName =
  | 'BalanceAbove'
  | 'BalanceBelow'
  | 'BalanceEquals'
  | 'BalanceNotEquals'
  | 'BlockNumberAbove'
  | 'BlockNumberBelow'
  | 'ObservationAbove'
  | 'ObservationBelow'
  | 'ObservationEquals'
  | 'ObservationNotEquals';

export type ActorAmountName =
  | 'Fixed'
  | 'PercentageOfCurrent'
  | 'PercentageAtOpening'
  | 'PercentageOfLastFunding'
  | 'AllAvailable';

const TASK_NAMES = [
  'Transfer',
  'SplitTransfer',
  'SwapIn',
  'SwapOut',
  'AddLiquidity',
  'RemoveLiquidity',
  'Burn',
  'Mint',
  'Stake',
  'DonateLiquidity',
  'Unstake',
  'StopCycle',
] as const satisfies readonly ActorTaskName[];

const PREDICATE_NAMES = [
  'BalanceAbove',
  'BalanceBelow',
  'BalanceEquals',
  'BalanceNotEquals',
  'BlockNumberAbove',
  'BlockNumberBelow',
  'ObservationAbove',
  'ObservationBelow',
  'ObservationEquals',
  'ObservationNotEquals',
] as const satisfies readonly ActorPredicateName[];

const AMOUNT_NAMES = [
  'Fixed',
  'PercentageOfCurrent',
  'PercentageAtOpening',
  'PercentageOfLastFunding',
  'AllAvailable',
] as const satisfies readonly ActorAmountName[];

export type ActorSemanticRecipient =
  | { kind: 'ActorSovereign' }
  | { kind: 'Explicit'; path: string }
  | { kind: 'AdapterDerived' };

export type ActorSemanticTask = {
  task: ActorTaskName;
  requiredAdapter:
    | 'None'
    | 'AssetOps'
    | 'DexOps'
    | 'StakingOps'
    | 'LiquidityOps';
  assetsRead: string[];
  assetsWritten: string[];
  readsAdapterDerivedAssets: boolean;
  writesAdapterDerivedAssets: boolean;
  recipients: ActorSemanticRecipient[];
  effects: Array<
    | 'Transfer'
    | 'SupplyBurn'
    | 'SupplyMint'
    | 'LiquidityMutation'
    | 'StakingMutation'
  >;
  availability: 'UserAndSystem' | 'SystemOnly';
  committedNonCompensatedEffects: boolean;
  successfulControl: 'Advance' | 'CompleteCycle';
  weightOwner: string;
  boundedInternalAlgorithm:
    | 'None'
    | 'PalletSplitFanout'
    | 'RuntimeAdapterContract';
  amountSurfaces: Array<{ role: string; path: string }>;
};

export type ActorSemanticPredicate = {
  predicate: ActorPredicateName;
  scaleIndex: number;
  observation:
    | 'BalanceComparison'
    | 'BlockNumberComparison'
    | 'ScalarObservationComparison';
  readSurface:
    | { kind: 'SpendableAssetBalance'; path: string }
    | { kind: 'CurrentBlockNumber' }
    | { kind: 'TypedObservation'; feedPath: string; maxAgeBlocksPath: string };
  pure: true;
  observationWindow: 'StepAttemptTime';
  boundedReadCount: 1;
};

export type ActorSemanticAmountResolution = {
  resolution: ActorAmountName;
  dataDependencies: Array<
    | 'ArtifactValue'
    | 'CurrentBalanceOrShares'
    | 'OpeningSnapshot'
    | 'LastFundingSnapshot'
    | 'TaskPolicyCapacity'
  >;
  minimumBalanceDependency: 'None' | 'TaskPolicy';
  feeReserveDependency: 'None' | 'TaskPolicy';
  valueObservationWindow:
    | 'ArtifactTime'
    | 'LogicalCycleStart'
    | 'StepAttemptTime';
  retryObservation: 'ReobserveLiveValue' | 'ReuseFrozenValueWithLiveCapacity';
};

export type ActorSemanticManifest = {
  format: 'deos.actor.semantic-manifest';
  formatVersion: 2;
  tasks: ActorSemanticTask[];
  predicates: ActorSemanticPredicate[];
  amountResolutions: ActorSemanticAmountResolution[];
};

function record(value: unknown, label: string): Record<string, unknown> {
  if (value == null || Array.isArray(value) || typeof value !== 'object') {
    throw new Error(`${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

function names(value: unknown, label: string) {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array`);
  return value.map((entry, index) => {
    const projected = record(entry, `${label}[${index}]`);
    if (typeof projected.task === 'string') return projected.task;
    if (typeof projected.predicate === 'string') return projected.predicate;
    if (typeof projected.resolution === 'string') return projected.resolution;
    throw new Error(`${label}[${index}] has no semantic identity`);
  });
}

function requireExactNames(
  actual: string[],
  expected: readonly string[],
  label: string,
) {
  if (
    actual.length !== expected.length ||
    actual.some((name, index) => name !== expected[index])
  ) {
    throw new Error(
      `${label} variants are unknown, missing, duplicated, or reordered`,
    );
  }
}

export function parseActorSemanticManifest(
  value: unknown,
): ActorSemanticManifest {
  const projected = record(value, 'Actors semantic manifest');
  if (projected.format !== 'deos.actor.semantic-manifest') {
    throw new Error('Unsupported Actors semantic manifest format');
  }
  if (projected.formatVersion !== 2) {
    throw new Error('Unsupported Actors semantic manifest version');
  }
  requireExactNames(names(projected.tasks, 'tasks'), TASK_NAMES, 'Task');
  requireExactNames(
    names(projected.predicates, 'predicates'),
    PREDICATE_NAMES,
    'Predicate',
  );
  const predicates = projected.predicates as Array<Record<string, unknown>>;
  predicates.forEach((predicate, index) => {
    if (predicate.scaleIndex !== index) {
      throw new Error(
        'Predicate SCALE indices are unknown, missing, or reordered',
      );
    }
  });
  requireExactNames(
    names(projected.amountResolutions, 'amountResolutions'),
    AMOUNT_NAMES,
    'AmountResolution',
  );
  return projected as ActorSemanticManifest;
}

export const ACTORS_SEMANTIC_MANIFEST =
  parseActorSemanticManifest(manifestJson);

const TASKS = new Map(
  ACTORS_SEMANTIC_MANIFEST.tasks.map((task) => [task.task, task]),
);
const PREDICATES = new Map(
  ACTORS_SEMANTIC_MANIFEST.predicates.map((predicate) => [
    predicate.predicate,
    predicate,
  ]),
);
const AMOUNTS = new Map(
  ACTORS_SEMANTIC_MANIFEST.amountResolutions.map((amount) => [
    amount.resolution,
    amount,
  ]),
);

export function actorTaskSemantics(task: string): ActorSemanticTask {
  const semantics = TASKS.get(task as ActorTaskName);
  if (semantics == null) throw new Error(`Unsupported Task variant: ${task}`);
  return semantics;
}

export function actorPredicateSemantics(
  predicate: string,
): ActorSemanticPredicate {
  const semantics = PREDICATES.get(predicate as ActorPredicateName);
  if (semantics == null) {
    throw new Error(`Unsupported Predicate variant: ${predicate}`);
  }
  return semantics;
}

export function actorAmountSemantics(
  resolution: string,
): ActorSemanticAmountResolution {
  const semantics = AMOUNTS.get(resolution as ActorAmountName);
  if (semantics == null) {
    throw new Error(`Unsupported AmountResolution variant: ${resolution}`);
  }
  return semantics;
}
