
//! Autogenerated weights for `pallet_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/benchmarks/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_oracle
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_oracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_oracle`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_oracle::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Oracle::Feeds` (r:1 w:1)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::FeedIds` (r:1 w:1)
	/// Proof: `Oracle::FeedIds` (`max_values`: Some(1), `max_size`: Some(17410), added: 17905, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ProducerFeeds` (r:1 w:1)
	/// Proof: `Oracle::ProducerFeeds` (`max_values`: None, `max_size`: Some(17067), added: 19542, mode: `MaxEncodedLen`)
	fn register_feed_existing_producer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `19554`
		//  Estimated: `20532`
		// Minimum execution time: 127_532_000 picoseconds.
		Weight::from_parts(146_111_000, 0)
			.saturating_add(Weight::from_parts(0, 20532))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:1)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::FeedIds` (r:1 w:1)
	/// Proof: `Oracle::FeedIds` (`max_values`: Some(1), `max_size`: Some(17410), added: 17905, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ProducerFeeds` (r:1 w:1)
	/// Proof: `Oracle::ProducerFeeds` (`max_values`: None, `max_size`: Some(17067), added: 19542, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ProducerIds` (r:1 w:1)
	/// Proof: `Oracle::ProducerIds` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	fn register_feed_new_producer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44394`
		//  Estimated: `34255`
		// Minimum execution time: 187_388_000 picoseconds.
		Weight::from_parts(215_185_000, 0)
			.saturating_add(Weight::from_parts(0, 44394))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:1)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn pause_feed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `3551`
		// Minimum execution time: 13_620_000 picoseconds.
		Weight::from_parts(15_366_000, 0)
			.saturating_add(Weight::from_parts(0, 3551))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:1)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn resume_feed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `3551`
		// Minimum execution time: 13_270_000 picoseconds.
		Weight::from_parts(15_435_000, 0)
			.saturating_add(Weight::from_parts(0, 3551))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:1)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn deactivate_feed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `310`
		//  Estimated: `3551`
		// Minimum execution time: 13_479_000 picoseconds.
		Weight::from_parts(15_365_000, 0)
			.saturating_add(Weight::from_parts(0, 3551))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn publish_last_value() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `693`
		//  Estimated: `3559`
		// Minimum execution time: 31_220_000 picoseconds.
		Weight::from_parts(33_733_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn publish_ema_changed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `772`
		//  Estimated: `3559`
		// Minimum execution time: 34_711_000 picoseconds.
		Weight::from_parts(37_156_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:1)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:1)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationListState` (r:1 w:1)
	/// Proof: `Actors::DirtyObservationListState` (`max_values`: Some(1), `max_size`: Some(58), added: 553, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn publish_ema_changed_primary_first() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `825`
		//  Estimated: `3559`
		// Minimum execution time: 43_861_000 picoseconds.
		Weight::from_parts(46_795_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:1)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:1)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn publish_ema_changed_primary_existing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `985`
		//  Estimated: `3559`
		// Minimum execution time: 43_372_000 picoseconds.
		Weight::from_parts(46_864_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingTransitionQueues` (r:1 w:1)
	/// Proof: `Actors::CrossingTransitionQueues` (`max_values`: None, `max_size`: Some(2595), added: 5070, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeeds` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeeds` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeedListState` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeedListState` (`max_values`: Some(1), `max_size`: Some(58), added: 553, mode: `MaxEncodedLen`)
	fn publish_ema_changed_secondary_first() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6060`
		// Minimum execution time: 46_165_000 picoseconds.
		Weight::from_parts(49_239_000, 0)
			.saturating_add(Weight::from_parts(0, 6060))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingTransitionQueues` (r:1 w:1)
	/// Proof: `Actors::CrossingTransitionQueues` (`max_values`: None, `max_size`: Some(2595), added: 5070, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeeds` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeeds` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeedListState` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeedListState` (`max_values`: Some(1), `max_size`: Some(58), added: 553, mode: `MaxEncodedLen`)
	fn publish_ema_changed_secondary_existing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6060`
		// Minimum execution time: 46_166_000 picoseconds.
		Weight::from_parts(49_099_000, 0)
			.saturating_add(Weight::from_parts(0, 6060))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:1)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:1)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationListState` (r:1 w:1)
	/// Proof: `Actors::DirtyObservationListState` (`max_values`: Some(1), `max_size`: Some(58), added: 553, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingTransitionQueues` (r:1 w:1)
	/// Proof: `Actors::CrossingTransitionQueues` (`max_values`: None, `max_size`: Some(2595), added: 5070, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeeds` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeeds` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeedListState` (r:1 w:1)
	/// Proof: `Actors::CrossingPendingFeedListState` (`max_values`: Some(1), `max_size`: Some(58), added: 553, mode: `MaxEncodedLen`)
	fn publish_ema_changed_combined() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `875`
		//  Estimated: `6060`
		// Minimum execution time: 55_315_000 picoseconds.
		Weight::from_parts(58_667_000, 0)
			.saturating_add(Weight::from_parts(0, 6060))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:0)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingFeedMembershipCount` (r:1 w:0)
	/// Proof: `Actors::CrossingFeedMembershipCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingTransitionQueues` (r:1 w:0)
	/// Proof: `Actors::CrossingTransitionQueues` (`max_values`: None, `max_size`: Some(2595), added: 5070, mode: `MaxEncodedLen`)
	/// Storage: `Actors::CrossingPendingFeeds` (r:1 w:0)
	/// Proof: `Actors::CrossingPendingFeeds` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn publish_ema_changed_secondary_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3517`
		//  Estimated: `6060`
		// Minimum execution time: 40_578_000 picoseconds.
		Weight::from_parts(45_188_000, 0)
			.saturating_add(Weight::from_parts(0, 6060))
			.saturating_add(T::DbWeight::get().reads(8))
	}
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn publish_ema_refresh() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `389`
		//  Estimated: `3551`
		// Minimum execution time: 19_975_000 picoseconds.
		Weight::from_parts(22_280_000, 0)
			.saturating_add(Weight::from_parts(0, 3551))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
