
//! Autogenerated weights for `pallet_tmc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/benchmarks/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_tmc
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_tmc.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tmc`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_tmc::WeightInfo for SubstrateWeight<T> {
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:1)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn create_curve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `6360`
		// Minimum execution time: 24_794_000 picoseconds.
		Weight::from_parts(26_680_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SovereignIndex` (r:1 w:0)
	/// Proof: `Actors::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorIdentities` (r:1 w:0)
	/// Proof: `Actors::ActorIdentities` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorHot` (r:1 w:0)
	/// Proof: `Actors::ActorHot` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorContract` (r:1 w:0)
	/// Proof: `Actors::ActorContract` (`max_values`: None, `max_size`: Some(8735), added: 11210, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorFunding` (r:1 w:0)
	/// Proof: `Actors::ActorFunding` (`max_values`: None, `max_size`: Some(286), added: 2761, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ContinuationState` (r:1 w:0)
	/// Proof: `Actors::ContinuationState` (`max_values`: None, `max_size`: Some(689), added: 3164, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn mint_with_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2362`
		//  Estimated: `12200`
		// Minimum execution time: 159_799_000 picoseconds.
		Weight::from_parts(164_130_000, 0)
			.saturating_add(Weight::from_parts(0, 12200))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
