
//! Autogenerated weights for `pallet_aaa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_aaa
// --extrinsic
// *
// --exclude-extrinsics
// pallet_aaa::process_remove_liquidity_max_k
// --exclude-extrinsics
// pallet_aaa::scheduler_cooldown_ineligible_idle
// --exclude-extrinsics
// pallet_aaa::scheduler_wakeup_sparse_gap_recovery
// --exclude-extrinsics
// pallet_aaa::close_aaa_on_close_execution_plan_complex
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress_100k
// --exclude-extrinsics
// pallet_aaa::circular_chain_100
// --exclude-extrinsics
// pallet_aaa::circular_chain_1000
// --exclude-extrinsics
// pallet_aaa::circular_chain_10000
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_aaa.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_aaa`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_aaa::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1912`
		//  Estimated: `12141`
		// Minimum execution time: 186_339_000 picoseconds.
		Weight::from_parts(211_693_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa_at_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1838`
		//  Estimated: `12141`
		// Minimum execution time: 183_336_000 picoseconds.
		Weight::from_parts(197_515_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn create_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `947`
		//  Estimated: `3651`
		// Minimum execution time: 50_007_000 picoseconds.
		Weight::from_parts(55_246_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ClosedSystemAaaIds` (r:1 w:1)
	/// Proof: `AAA::ClosedSystemAaaIds` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:0)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn reopen_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `992`
		//  Estimated: `3651`
		// Minimum execution time: 55_246_000 picoseconds.
		Weight::from_parts(59_157_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn create_dormant_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `999`
		//  Estimated: `3651`
		// Minimum execution time: 42_813_000 picoseconds.
		Weight::from_parts(46_096_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn activate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `697`
		//  Estimated: `3651`
		// Minimum execution time: 42_744_000 picoseconds.
		Weight::from_parts(46_655_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:0 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn deactivate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1043`
		//  Estimated: `12141`
		// Minimum execution time: 40_998_000 picoseconds.
		Weight::from_parts(44_420_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn pause_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `823`
		//  Estimated: `12141`
		// Minimum execution time: 28_985_000 picoseconds.
		Weight::from_parts(31_709_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn resume_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `828`
		//  Estimated: `12141`
		// Minimum execution time: 32_896_000 picoseconds.
		Weight::from_parts(35_829_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	fn manual_trigger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `842`
		//  Estimated: `12141`
		// Minimum execution time: 42_115_000 picoseconds.
		Weight::from_parts(46_654_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:33 w:33)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:33 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ClosedSystemAaaIds` (r:0 w:1)
	/// Proof: `AAA::ClosedSystemAaaIds` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn close_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4595`
		//  Estimated: `86889`
		// Minimum execution time: 2_132_359_000 picoseconds.
		Weight::from_parts(2_216_101_000, 0)
			.saturating_add(Weight::from_parts(0, 86889))
			.saturating_add(T::DbWeight::get().reads(73))
			.saturating_add(T::DbWeight::get().writes(41))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn update_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `823`
		//  Estimated: `12141`
		// Minimum execution time: 36_319_000 picoseconds.
		Weight::from_parts(39_740_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_funding_source_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `960`
		//  Estimated: `12141`
		// Minimum execution time: 38_692_000 picoseconds.
		Weight::from_parts(42_884_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_execution_plan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1330`
		//  Estimated: `12141`
		// Minimum execution time: 47_074_000 picoseconds.
		Weight::from_parts(52_382_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_on_close_execution_plan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `960`
		//  Estimated: `12141`
		// Minimum execution time: 41_137_000 picoseconds.
		Weight::from_parts(45_397_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:0 w:1)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_global_circuit_breaker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_543_000 picoseconds.
		Weight::from_parts(9_429_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:0)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:1)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_active_actor_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `1489`
		// Minimum execution time: 13_340_000 picoseconds.
		Weight::from_parts(15_365_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn permissionless_sweep() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1001`
		//  Estimated: `12141`
		// Minimum execution time: 30_032_000 picoseconds.
		Weight::from_parts(32_687_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `AAA::ActorHot` (r:5 w:5)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:5 w:5)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:5 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:5 w:5)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:5 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:5 w:5)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:5)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:0 w:5)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 5]`.
	fn permissionless_sweep_many(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `994 + n * (384 ±0)`
		//  Estimated: `1489 + n * (11151 ±0)`
		// Minimum execution time: 73_823_000 picoseconds.
		Weight::from_parts(28_210_750, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			// Standard Error: 56_256
			.saturating_add(Weight::from_parts(51_466_899, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 11151).saturating_mul(n.into()))
	}
	/// Storage: `AAA::ActorHot` (r:2 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:2 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:10 w:10)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:2 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:10 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 3]`.
	/// The range of component `l` is `[2, 8]`.
	fn close_aaa_user_fee_bearing_tail(s: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2350 + l * (82 ±0) + s * (127 ±0)`
		//  Estimated: `23292 + l * (2694 ±24) + s * (1458 ±64)`
		// Minimum execution time: 683_479_000 picoseconds.
		Weight::from_parts(54_292_726, 0)
			.saturating_add(Weight::from_parts(0, 23292))
			// Standard Error: 344_638
			.saturating_add(Weight::from_parts(195_773_909, 0).saturating_mul(s.into()))
			// Standard Error: 133_530
			.saturating_add(Weight::from_parts(58_059_951, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 2694).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 1458).saturating_mul(s.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn fee_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1647`
		//  Estimated: `12141`
		// Minimum execution time: 109_093_000 picoseconds.
		Weight::from_parts(112_517_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn task_simple_asset_op() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721994`
		//  Estimated: `743463`
		// Minimum execution time: 1_314_574_000 picoseconds.
		Weight::from_parts(1_410_189_000, 0)
			.saturating_add(Weight::from_parts(0, 743463))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `AAA::SovereignIndex` (r:8 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:8 w:8)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:8 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:8 w:8)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:8 w:8)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:8 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:8)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[2, 8]`.
	fn task_split_transfer(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721539 + l * (431 ±0)`
		//  Estimated: `743463 + l * (11151 ±0)`
		// Minimum execution time: 2_445_463_000 picoseconds.
		Weight::from_parts(411_584_842, 0)
			.saturating_add(Weight::from_parts(0, 743463))
			// Standard Error: 2_481_070
			.saturating_add(Weight::from_parts(1_104_999_224, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 11151).saturating_mul(l.into()))
	}
	/// Storage: `AssetRegistry::ForeignAssetMapping` (r:1 w:0)
	/// Proof: `AssetRegistry::ForeignAssetMapping` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn xcm_asset_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `722366`
		//  Estimated: `743463`
		// Minimum execution time: 1_299_000_000 picoseconds.
		Weight::from_parts(1_394_753_000, 0)
			.saturating_add(Weight::from_parts(0, 743463))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:1)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::NextPoolAssetId` (r:1 w:1)
	/// Proof: `AssetConversion::NextPoolAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn task_add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `771`
		//  Estimated: `11426`
		// Minimum execution time: 236_626_000 picoseconds.
		Weight::from_parts(248_639_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_donate_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1631`
		//  Estimated: `14035`
		// Minimum execution time: 197_026_000 picoseconds.
		Weight::from_parts(206_175_000, 0)
			.saturating_add(Weight::from_parts(0, 14035))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `AssetConversion::Pools` (r:32 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4504`
		//  Estimated: `81150`
		// Minimum execution time: 310_170_000 picoseconds.
		Weight::from_parts(340_063_000, 0)
			.saturating_add(Weight::from_parts(0, 81150))
			.saturating_add(T::DbWeight::get().reads(38))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1252`
		//  Estimated: `11699`
		// Minimum execution time: 105_742_000 picoseconds.
		Weight::from_parts(110_351_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1594`
		//  Estimated: `11699`
		// Minimum execution time: 126_624_000 picoseconds.
		Weight::from_parts(131_933_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_in() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2382`
		//  Estimated: `12141`
		// Minimum execution time: 303_675_000 picoseconds.
		Weight::from_parts(319_459_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2382`
		//  Estimated: `12141`
		// Minimum execution time: 852_776_000 picoseconds.
		Weight::from_parts(900_129_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::LastIngressIngestBlock` (r:1 w:1)
	/// Proof: `AAA::LastIngressIngestBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IdleStarvationBlocks` (r:1 w:1)
	/// Proof: `AAA::IdleStarvationBlocks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn scheduler_on_idle_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `1493`
		// Minimum execution time: 14_736_000 picoseconds.
		Weight::from_parts(16_692_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::NextAaaId` (r:1 w:0)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SweepCursor` (r:1 w:0)
	/// Proof: `AAA::SweepCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:1 w:0)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn scheduler_zombie_sweep_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `406`
		//  Estimated: `3490`
		// Minimum execution time: 10_546_000 picoseconds.
		Weight::from_parts(12_362_000, 0)
			.saturating_add(Weight::from_parts(0, 3490))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn scheduler_actor_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `706`
		//  Estimated: `12141`
		// Minimum execution time: 20_953_000 picoseconds.
		Weight::from_parts(23_188_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_existing_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1716`
		//  Estimated: `5181`
		// Minimum execution time: 28_636_000 picoseconds.
		Weight::from_parts(31_988_000, 0)
			.saturating_add(Weight::from_parts(0, 5181))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_new_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1202`
		//  Estimated: `4667`
		// Minimum execution time: 25_004_000 picoseconds.
		Weight::from_parts(28_146_000, 0)
			.saturating_add(Weight::from_parts(0, 4667))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:0)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	fn scheduler_paged_consume_preserve_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `662`
		//  Estimated: `4127`
		// Minimum execution time: 19_416_000 picoseconds.
		Weight::from_parts(21_511_000, 0)
			.saturating_add(Weight::from_parts(0, 4127))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	fn scheduler_paged_consume_delete_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `654`
		//  Estimated: `4119`
		// Minimum execution time: 21_022_000 picoseconds.
		Weight::from_parts(22_978_000, 0)
			.saturating_add(Weight::from_parts(0, 4119))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_tombstone_drain(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `584 + n * (8 ±0)`
		//  Estimated: `2903 + n * (2484 ±0)`
		// Minimum execution time: 19_626_000 picoseconds.
		Weight::from_parts(20_115_000, 0)
			.saturating_add(Weight::from_parts(0, 2903))
			// Standard Error: 2_937
			.saturating_add(Weight::from_parts(2_310_537, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 2484).saturating_mul(n.into()))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:5000)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_mixed_scan(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `789 + n * (86 ±0)`
		//  Estimated: `3092 + n * (2562 ±0)`
		// Minimum execution time: 23_467_000 picoseconds.
		Weight::from_parts(24_026_000, 0)
			.saturating_add(Weight::from_parts(0, 3092))
			// Standard Error: 19_408
			.saturating_add(Weight::from_parts(12_593_062, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2562).saturating_mul(n.into()))
	}
	/// Storage: `AAA::MinWakeupBlock` (r:1 w:1)
	/// Proof: `AAA::MinWakeupBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:16 w:16)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:999 w:999)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::ActorProgram` (r:999 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `Measured`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `Measured`)
	/// Storage: `AAA::ActorFunding` (r:999 w:999)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// The range of component `n` is `[1, 1000]`.
	fn scheduler_paged_execute_cheap(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873 + n * (254 ±0)`
		//  Estimated: `4332 + n * (2730 ±0)`
		// Minimum execution time: 92_471_000 picoseconds.
		Weight::from_parts(97_779_000, 0)
			.saturating_add(Weight::from_parts(0, 4332))
			// Standard Error: 81_923
			.saturating_add(Weight::from_parts(65_474_913, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2730).saturating_mul(n.into()))
	}
	/// Storage: `AAA::MinWakeupBlock` (r:1 w:1)
	/// Proof: `AAA::MinWakeupBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:2 w:2)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:64 w:64)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:64 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:64)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 64]`.
	fn scheduler_wakeup_dense_due_drain(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556 + n * (40 ±0)`
		//  Estimated: `159726 + n * (2661 ±34)`
		// Minimum execution time: 14_458_000 picoseconds.
		Weight::from_parts(15_013_534, 0)
			.saturating_add(Weight::from_parts(0, 159726))
			// Standard Error: 6_209
			.saturating_add(Weight::from_parts(14_854_525, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2661).saturating_mul(n.into()))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::MinWakeupBlock` (r:1 w:1)
	/// Proof: `AAA::MinWakeupBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[0, 9]`.
	fn scheduler_wakeup_spillover_probe(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `955 + b * (80032 ±0)`
		//  Estimated: `86958 + b * (81168 ±0)`
		// Minimum execution time: 27_099_000 picoseconds.
		Weight::from_parts(15_394_546, 0)
			.saturating_add(Weight::from_parts(0, 86958))
			// Standard Error: 128_546
			.saturating_add(Weight::from_parts(130_001_701, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 81168).saturating_mul(b.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `710`
		//  Estimated: `3521`
		// Minimum execution time: 13_060_000 picoseconds.
		Weight::from_parts(14_737_000, 0)
			.saturating_add(Weight::from_parts(0, 3521))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_notify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721650`
		//  Estimated: `743463`
		// Minimum execution time: 1_242_357_000 picoseconds.
		Weight::from_parts(1_301_234_000, 0)
			.saturating_add(Weight::from_parts(0, 743463))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 10]`.
	fn funding_batch_promotion(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425 + a * (37 ±0)`
		//  Estimated: `4426`
		// Minimum execution time: 19_067_000 picoseconds.
		Weight::from_parts(18_532_861, 0)
			.saturating_add(Weight::from_parts(0, 4426))
			// Standard Error: 1_399
			.saturating_add(Weight::from_parts(2_369_588, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::IngressOverflowLen` (r:1 w:0)
	/// Proof: `AAA::IngressOverflowLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn compatibility_ingress_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `311`
		//  Estimated: `1489`
		// Minimum execution time: 5_587_000 picoseconds.
		Weight::from_parts(7_194_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::IngressOverflowHead` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowHead` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IngressOverflowLen` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IngressOverflowSlots` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowSlots` (`max_values`: None, `max_size`: Some(83), added: 2558, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ScheduledWakeupBlock` (r:1 w:0)
	/// Proof: `AAA::ScheduledWakeupBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupIndex` (r:9 w:9)
	/// Proof: `AAA::WakeupIndex` (`max_values`: None, `max_size`: Some(80022), added: 82497, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupScheduleDrops` (r:1 w:1)
	/// Proof: `AAA::WakeupScheduleDrops` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupRetryPending` (r:0 w:1)
	/// Proof: `AAA::WakeupRetryPending` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn compatibility_ingress_drain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721539`
		//  Estimated: `743463`
		// Minimum execution time: 1_179_499_000 picoseconds.
		Weight::from_parts(1_237_468_000, 0)
			.saturating_add(Weight::from_parts(0, 743463))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(15))
	}
}
