
//! Autogenerated weights for `pallet_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-13, STEPS: `100`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/benchmarks/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_staking
// --extrinsic
// *
// --steps
// 100
// --repeat
// 50
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/.pallet_staking.weights.NZnF3W

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_staking`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_staking::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::LiveStakedAssetBaseAssets` (r:1 w:1)
	/// Proof: `Staking::LiveStakedAssetBaseAssets` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn register_staking_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `773`
		//  Estimated: `6360`
		// Minimum execution time: 66_770_000 picoseconds.
		Weight::from_parts(69_214_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn sync_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `548`
		//  Estimated: `3599`
		// Minimum execution time: 27_587_000 picoseconds.
		Weight::from_parts(29_823_000, 0)
			.saturating_add(Weight::from_parts(0, 3599))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1216`
		//  Estimated: `8817`
		// Minimum execution time: 101_411_000 picoseconds.
		Weight::from_parts(109_513_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1278`
		//  Estimated: `8817`
		// Minimum execution time: 107_208_000 picoseconds.
		Weight::from_parts(113_774_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn recover_unowned_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1025`
		//  Estimated: `6208`
		// Minimum execution time: 81_018_000 picoseconds.
		Weight::from_parts(83_951_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeLpLocks` (r:1 w:1)
	/// Proof: `Staking::NativeLpLocks` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeNominationOperators` (r:1 w:0)
	/// Proof: `Staking::NativeNominationOperators` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityParticipants` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityParticipants` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::OperatorNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeCollatorLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeCollatorLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeLpLocked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn lock_native_lp_for_collator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1930`
		//  Estimated: `6208`
		// Minimum execution time: 116_706_000 picoseconds.
		Weight::from_parts(120_199_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Governance::GovernanceLocks` (r:1 w:0)
	/// Proof: `Governance::GovernanceLocks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeLpLocks` (r:1 w:1)
	/// Proof: `Staking::NativeLpLocks` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeNominationOperators` (r:1 w:0)
	/// Proof: `Staking::NativeNominationOperators` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityParticipants` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityParticipants` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::OperatorNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeCollatorLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeCollatorLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeLpLocked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::PendingNativeLpUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeLpUnlocks` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn request_unlock_native_lp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `853`
		//  Estimated: `4687`
		// Minimum execution time: 65_721_000 picoseconds.
		Weight::from_parts(68_655_000, 0)
			.saturating_add(Weight::from_parts(0, 4687))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Staking::PendingNativeLpUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeLpUnlocks` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unlocked_native_lp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1256`
		//  Estimated: `6208`
		// Minimum execution time: 81_436_000 picoseconds.
		Weight::from_parts(84_020_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeLpLocks` (r:2 w:2)
	/// Proof: `Staking::NativeLpLocks` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeNominationOperators` (r:1 w:1)
	/// Proof: `Staking::NativeNominationOperators` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityParticipants` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityParticipants` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorNativeLpLocked` (r:2 w:2)
	/// Proof: `Staking::OperatorNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn redelegate_native_lp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `814`
		//  Estimated: `6172`
		// Minimum execution time: 55_245_000 picoseconds.
		Weight::from_parts(57_899_000, 0)
			.saturating_add(Weight::from_parts(0, 6172))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AssetConversion::Pools` (r:1 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeGovernanceLpLocks` (r:1 w:1)
	/// Proof: `Staking::NativeGovernanceLpLocks` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeLpLocked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn lock_native_lp_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1367`
		//  Estimated: `6208`
		// Minimum execution time: 90_795_000 picoseconds.
		Weight::from_parts(94_497_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Governance::GovernanceLocks` (r:1 w:0)
	/// Proof: `Governance::GovernanceLocks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeGovernanceLpLocks` (r:1 w:1)
	/// Proof: `Staking::NativeGovernanceLpLocks` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeLpLocked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::PendingNativeGovernanceLpUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeGovernanceLpUnlocks` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn request_unlock_native_lp_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `404`
		//  Estimated: `3537`
		// Minimum execution time: 37_156_000 picoseconds.
		Weight::from_parts(39_391_000, 0)
			.saturating_add(Weight::from_parts(0, 3537))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::PendingNativeGovernanceLpUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeGovernanceLpUnlocks` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unlocked_native_lp_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1159`
		//  Estimated: `6208`
		// Minimum execution time: 75_988_000 picoseconds.
		Weight::from_parts(78_852_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Staking::NativeGovernanceAssetLocked` (r:1 w:1)
	/// Proof: `Staking::NativeGovernanceAssetLocked` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeGovernanceAssetLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeGovernanceAssetLocked` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn lock_native_asset_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1098`
		//  Estimated: `6208`
		// Minimum execution time: 85_347_000 picoseconds.
		Weight::from_parts(88_280_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Governance::GovernanceLocks` (r:1 w:0)
	/// Proof: `Governance::GovernanceLocks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeGovernanceAssetLocked` (r:1 w:1)
	/// Proof: `Staking::NativeGovernanceAssetLocked` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeGovernanceAssetLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeGovernanceAssetLocked` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::PendingNativeGovernanceAssetUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeGovernanceAssetUnlocks` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn request_unlock_native_asset_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3557`
		// Minimum execution time: 34_781_000 picoseconds.
		Weight::from_parts(36_877_000, 0)
			.saturating_add(Weight::from_parts(0, 3557))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::PendingNativeGovernanceAssetUnlocks` (r:1 w:1)
	/// Proof: `Staking::PendingNativeGovernanceAssetUnlocks` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unlocked_native_asset_for_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `971`
		//  Estimated: `6208`
		// Minimum execution time: 78_572_000 picoseconds.
		Weight::from_parts(81_366_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::ActiveNativeSecurityEpochSnapshot` (r:1 w:0)
	/// Proof: `Staking::ActiveNativeSecurityEpochSnapshot` (`max_values`: Some(1), `max_size`: Some(12824), added: 13319, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardLiability` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardLiability` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_native_security_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `802`
		//  Estimated: `16309`
		// Minimum execution time: 84_370_000 picoseconds.
		Weight::from_parts(88_281_000, 0)
			.saturating_add(Weight::from_parts(0, 16309))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardClaims` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardClaims` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardLiability` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardLiability` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn claim_native_security_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `890`
		//  Estimated: `16309`
		// Minimum execution time: 87_652_000 picoseconds.
		Weight::from_parts(91_494_000, 0)
			.saturating_add(Weight::from_parts(0, 16309))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:12 w:0)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:12 w:12)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardClaims` (r:12 w:12)
	/// Proof: `Staking::NativeSecurityRewardClaims` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardLiability` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardLiability` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 12]`.
	fn claim_native_security_reward_batch(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `546 + c * (206 ±0)`
		//  Estimated: `6196 + c * (15319 ±0)`
		// Minimum execution time: 82_903_000 picoseconds.
		Weight::from_parts(68_928_304, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 23_302
			.saturating_add(Weight::from_parts(17_726_905, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 15319).saturating_mul(c.into()))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardClaims` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardClaims` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardLiability` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardLiability` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:7 w:7)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:3 w:3)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeLpLocks` (r:1 w:1)
	/// Proof: `Staking::NativeLpLocks` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeNominationOperators` (r:1 w:1)
	/// Proof: `Staking::NativeNominationOperators` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityParticipants` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityParticipants` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OperatorNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::OperatorNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::AccountNativeCollatorLpLocked` (r:1 w:1)
	/// Proof: `Staking::AccountNativeCollatorLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::TotalNativeLpLocked` (r:1 w:1)
	/// Proof: `Staking::TotalNativeLpLocked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn claim_and_compound_native_security_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2493`
		//  Estimated: `19253`
		// Minimum execution time: 443_778_000 picoseconds.
		Weight::from_parts(463_265_000, 0)
			.saturating_add(Weight::from_parts(0, 19253))
			.saturating_add(T::DbWeight::get().reads(27))
			.saturating_add(T::DbWeight::get().writes(23))
	}
	/// Storage: `Session::CurrentIndex` (r:1 w:0)
	/// Proof: `Session::CurrentIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardLiability` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardLiability` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn expire_native_security_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739`
		//  Estimated: `6196`
		// Minimum execution time: 75_081_000 picoseconds.
		Weight::from_parts(77_734_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::NativeSecurityRewardPots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityRewardClaims` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityRewardClaims` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:0 w:1)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `MaxEncodedLen`)
	fn cleanup_expired_native_security_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `372`
		//  Estimated: `3534`
		// Minimum execution time: 21_512_000 picoseconds.
		Weight::from_parts(23_536_000, 0)
			.saturating_add(Weight::from_parts(0, 3534))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `Measured`)
	/// Storage: `CollatorSelection::CandidateList` (r:1 w:0)
	/// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(4802), added: 5297, mode: `Measured`)
	/// Storage: `Staking::OperatorNativeLpLocked` (r:100 w:0)
	/// Proof: `Staking::OperatorNativeLpLocked` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `Measured`)
	/// Storage: `AssetConversion::Pools` (r:1 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:3 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `Measured`)
	/// Storage: `Assets::Account` (r:2 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `Measured`)
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityParticipants` (r:1 w:0)
	/// Proof: `Staking::NativeSecurityParticipants` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `Measured`)
	/// Storage: `Staking::NativeNominationOperators` (r:100 w:0)
	/// Proof: `Staking::NativeNominationOperators` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `Measured`)
	/// Storage: `Staking::NativeLpLocks` (r:100 w:0)
	/// Proof: `Staking::NativeLpLocks` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `Measured`)
	/// Storage: `Governance::WinningVoteWindows` (r:100 w:0)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityEpochSnapshots` (r:1 w:1)
	/// Proof: `Staking::NativeSecurityEpochSnapshots` (`max_values`: None, `max_size`: Some(12844), added: 15319, mode: `Measured`)
	/// Storage: `Staking::NativeSecurityRewardPots` (r:0 w:1)
	/// Proof: `Staking::NativeSecurityRewardPots` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `Measured`)
	/// The range of component `p` is `[1, 100]`.
	fn open_native_security_epoch(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2911 + p * (374 ±0)`
		//  Estimated: `11101 + p * (2853 ±0)`
		// Minimum execution time: 104_274_000 picoseconds.
		Weight::from_parts(28_597_468, 0)
			.saturating_add(Weight::from_parts(0, 11101))
			// Standard Error: 34_018
			.saturating_add(Weight::from_parts(50_785_874, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 2853).saturating_mul(p.into()))
	}
}
