
//! Autogenerated weights for `pallet_aaa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_aaa
// --extrinsic
// *
// --exclude-extrinsics
// pallet_aaa::process_remove_liquidity_max_k
// --exclude-extrinsics
// pallet_aaa::scheduler_cooldown_ineligible_idle
// --exclude-extrinsics
// pallet_aaa::scheduler_wakeup_sparse_gap_recovery
// --exclude-extrinsics
// pallet_aaa::close_aaa_on_close_execution_plan_complex
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress_100k
// --exclude-extrinsics
// pallet_aaa::circular_chain_100
// --exclude-extrinsics
// pallet_aaa::circular_chain_1000
// --exclude-extrinsics
// pallet_aaa::circular_chain_10000
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_aaa.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_aaa`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_aaa::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1911`
		//  Estimated: `12141`
		// Minimum execution time: 184_803_000 picoseconds.
		Weight::from_parts(190_600_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa_at_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1837`
		//  Estimated: `12141`
		// Minimum execution time: 182_149_000 picoseconds.
		Weight::from_parts(187_387_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn create_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `947`
		//  Estimated: `3651`
		// Minimum execution time: 50_077_000 picoseconds.
		Weight::from_parts(53_848_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ClosedSystemAaaIds` (r:1 w:1)
	/// Proof: `AAA::ClosedSystemAaaIds` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:0)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn reopen_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `992`
		//  Estimated: `3651`
		// Minimum execution time: 55_804_000 picoseconds.
		Weight::from_parts(58_179_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn create_dormant_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `999`
		//  Estimated: `3651`
		// Minimum execution time: 42_813_000 picoseconds.
		Weight::from_parts(45_188_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn activate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `697`
		//  Estimated: `3651`
		// Minimum execution time: 42_604_000 picoseconds.
		Weight::from_parts(44_629_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:0 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn deactivate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `724`
		//  Estimated: `12141`
		// Minimum execution time: 37_086_000 picoseconds.
		Weight::from_parts(39_112_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn pause_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `12141`
		// Minimum execution time: 28_705_000 picoseconds.
		Weight::from_parts(30_522_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn resume_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `827`
		//  Estimated: `12141`
		// Minimum execution time: 32_895_000 picoseconds.
		Weight::from_parts(34_781_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	fn manual_trigger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `841`
		//  Estimated: `12141`
		// Minimum execution time: 42_743_000 picoseconds.
		Weight::from_parts(44_699_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:33 w:33)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:33 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ClosedSystemAaaIds` (r:0 w:1)
	/// Proof: `AAA::ClosedSystemAaaIds` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn close_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4595`
		//  Estimated: `86889`
		// Minimum execution time: 2_102_676_000 picoseconds.
		Weight::from_parts(2_143_325_000, 0)
			.saturating_add(Weight::from_parts(0, 86889))
			.saturating_add(T::DbWeight::get().reads(72))
			.saturating_add(T::DbWeight::get().writes(40))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	fn update_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `12141`
		// Minimum execution time: 36_388_000 picoseconds.
		Weight::from_parts(38_274_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_funding_source_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `959`
		//  Estimated: `12141`
		// Minimum execution time: 38_692_000 picoseconds.
		Weight::from_parts(40_788_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_execution_plan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1329`
		//  Estimated: `12141`
		// Minimum execution time: 47_492_000 picoseconds.
		Weight::from_parts(49_518_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	fn update_on_close_execution_plan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `959`
		//  Estimated: `12141`
		// Minimum execution time: 40_997_000 picoseconds.
		Weight::from_parts(43_023_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:0 w:1)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_global_circuit_breaker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_543_000 picoseconds.
		Weight::from_parts(9_150_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:0)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:1)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_active_actor_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `1489`
		// Minimum execution time: 13_409_000 picoseconds.
		Weight::from_parts(15_226_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn permissionless_sweep() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1000`
		//  Estimated: `12141`
		// Minimum execution time: 30_312_000 picoseconds.
		Weight::from_parts(31_988_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `AAA::ActorHot` (r:5 w:5)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:5 w:5)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:5 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:5 w:5)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:5 w:5)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:0 w:5)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 5]`.
	fn permissionless_sweep_many(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `685 + n * (369 ±0)`
		//  Estimated: `1489 + n * (11151 ±0)`
		// Minimum execution time: 69_214_000 picoseconds.
		Weight::from_parts(26_091_888, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			// Standard Error: 15_234
			.saturating_add(Weight::from_parts(46_066_084, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((5_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 11151).saturating_mul(n.into()))
	}
	/// Storage: `AAA::ActorHot` (r:2 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:2 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:10 w:10)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:2 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:10 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 3]`.
	/// The range of component `l` is `[2, 8]`.
	fn close_aaa_user_fee_bearing_tail(s: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2348 + l * (82 ±0) + s * (127 ±0)`
		//  Estimated: `23292 + l * (2694 ±24) + s * (1458 ±64)`
		// Minimum execution time: 676_215_000 picoseconds.
		Weight::from_parts(50_440_663, 0)
			.saturating_add(Weight::from_parts(0, 23292))
			// Standard Error: 227_372
			.saturating_add(Weight::from_parts(193_150_445, 0).saturating_mul(s.into()))
			// Standard Error: 88_095
			.saturating_add(Weight::from_parts(56_882_697, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 2694).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 1458).saturating_mul(s.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn fee_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1647`
		//  Estimated: `12141`
		// Minimum execution time: 108_605_000 picoseconds.
		Weight::from_parts(111_469_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn task_simple_asset_op() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1687`
		//  Estimated: `12141`
		// Minimum execution time: 147_717_000 picoseconds.
		Weight::from_parts(150_720_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::SovereignIndex` (r:8 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:8 w:8)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:8 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:8 w:8)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:8 w:8)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[2, 8]`.
	fn task_split_transfer(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1232 + l * (431 ±0)`
		//  Estimated: `3675 + l * (11151 ±0)`
		// Minimum execution time: 255_903_000 picoseconds.
		Weight::from_parts(45_579_142, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			// Standard Error: 40_769
			.saturating_add(Weight::from_parts(110_101_781, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 11151).saturating_mul(l.into()))
	}
	/// Storage: `AssetRegistry::ForeignAssetMapping` (r:1 w:0)
	/// Proof: `AssetRegistry::ForeignAssetMapping` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn xcm_asset_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2059`
		//  Estimated: `12141`
		// Minimum execution time: 127_183_000 picoseconds.
		Weight::from_parts(130_535_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:1)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::NextPoolAssetId` (r:1 w:1)
	/// Proof: `AssetConversion::NextPoolAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn task_add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `771`
		//  Estimated: `11426`
		// Minimum execution time: 236_975_000 picoseconds.
		Weight::from_parts(241_724_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_donate_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1631`
		//  Estimated: `14035`
		// Minimum execution time: 197_584_000 picoseconds.
		Weight::from_parts(208_201_000, 0)
			.saturating_add(Weight::from_parts(0, 14035))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `AssetConversion::Pools` (r:32 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4504`
		//  Estimated: `81150`
		// Minimum execution time: 309_122_000 picoseconds.
		Weight::from_parts(336_012_000, 0)
			.saturating_add(Weight::from_parts(0, 81150))
			.saturating_add(T::DbWeight::get().reads(38))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1252`
		//  Estimated: `11699`
		// Minimum execution time: 106_161_000 picoseconds.
		Weight::from_parts(109_164_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1594`
		//  Estimated: `11699`
		// Minimum execution time: 127_602_000 picoseconds.
		Weight::from_parts(131_164_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_in() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2382`
		//  Estimated: `12141`
		// Minimum execution time: 303_186_000 picoseconds.
		Weight::from_parts(314_710_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2382`
		//  Estimated: `12141`
		// Minimum execution time: 853_265_000 picoseconds.
		Weight::from_parts(886_790_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::LastIngressIngestBlock` (r:1 w:1)
	/// Proof: `AAA::LastIngressIngestBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IdleStarvationBlocks` (r:1 w:1)
	/// Proof: `AAA::IdleStarvationBlocks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn scheduler_on_idle_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `1493`
		// Minimum execution time: 14_527_000 picoseconds.
		Weight::from_parts(16_273_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::NextAaaId` (r:1 w:0)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SweepCursor` (r:1 w:0)
	/// Proof: `AAA::SweepCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn scheduler_zombie_sweep_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `1493`
		// Minimum execution time: 7_124_000 picoseconds.
		Weight::from_parts(8_730_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	fn scheduler_actor_hot_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `3651`
		// Minimum execution time: 9_010_000 picoseconds.
		Weight::from_parts(10_616_000, 0)
			.saturating_add(Weight::from_parts(0, 3651))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn scheduler_actor_program_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `12141`
		// Minimum execution time: 15_715_000 picoseconds.
		Weight::from_parts(17_600_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_existing_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1716`
		//  Estimated: `5181`
		// Minimum execution time: 28_984_000 picoseconds.
		Weight::from_parts(31_499_000, 0)
			.saturating_add(Weight::from_parts(0, 5181))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_new_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1202`
		//  Estimated: `4667`
		// Minimum execution time: 25_563_000 picoseconds.
		Weight::from_parts(27_658_000, 0)
			.saturating_add(Weight::from_parts(0, 4667))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	fn scheduler_wakeup_append_existing_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1402`
		//  Estimated: `4867`
		// Minimum execution time: 33_734_000 picoseconds.
		Weight::from_parts(36_318_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	fn scheduler_wakeup_append_new_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1445`
		//  Estimated: `4910`
		// Minimum execution time: 35_690_000 picoseconds.
		Weight::from_parts(38_553_000, 0)
			.saturating_add(Weight::from_parts(0, 4910))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:2 w:2)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_replace_exact() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `762`
		//  Estimated: `6702`
		// Minimum execution time: 59_156_000 picoseconds.
		Weight::from_parts(61_881_000, 0)
			.saturating_add(Weight::from_parts(0, 6702))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:3 w:3)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	fn scheduler_wakeup_invalidate_middle_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1772`
		//  Estimated: `10187`
		// Minimum execution time: 46_096_000 picoseconds.
		Weight::from_parts(50_566_000, 0)
			.saturating_add(Weight::from_parts(0, 10187))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:16 w:16)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	fn scheduler_wakeup_drain_partial_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3882`
		//  Estimated: `44472`
		// Minimum execution time: 133_888_000 picoseconds.
		Weight::from_parts(146_809_000, 0)
			.saturating_add(Weight::from_parts(0, 44472))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(18))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:32 w:32)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_full_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6155`
		//  Estimated: `86345`
		// Minimum execution time: 249_337_000 picoseconds.
		Weight::from_parts(268_264_000, 0)
			.saturating_add(Weight::from_parts(0, 86345))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(36))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:2 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:33 w:33)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_dense_boundary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6390`
		//  Estimated: `89055`
		// Minimum execution time: 265_820_000 picoseconds.
		Weight::from_parts(283_281_000, 0)
			.saturating_add(Weight::from_parts(0, 89055))
			.saturating_add(T::DbWeight::get().reads(38))
			.saturating_add(T::DbWeight::get().writes(38))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:32 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_stale_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5643`
		//  Estimated: `85833`
		// Minimum execution time: 159_450_000 picoseconds.
		Weight::from_parts(168_739_000, 0)
			.saturating_add(Weight::from_parts(0, 85833))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::WakeupBuckets` (r:14 w:14)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:10 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_insert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6167`
		//  Estimated: `41807`
		// Minimum execution time: 321_276_000 picoseconds.
		Weight::from_parts(338_527_000, 0)
			.saturating_add(Weight::from_parts(0, 41807))
			.saturating_add(T::DbWeight::get().reads(25))
			.saturating_add(T::DbWeight::get().writes(25))
	}
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:15 w:15)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	fn scheduler_wakeup_cursor_pop_min() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10659`
		//  Estimated: `56199`
		// Minimum execution time: 433_372_000 picoseconds.
		Weight::from_parts(463_893_000, 0)
			.saturating_add(Weight::from_parts(0, 56199))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(26))
	}
	/// Storage: `AAA::WakeupBuckets` (r:14 w:14)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_remove_exact() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10227`
		//  Estimated: `55767`
		// Minimum execution time: 408_299_000 picoseconds.
		Weight::from_parts(427_436_000, 0)
			.saturating_add(Weight::from_parts(0, 55767))
			.saturating_add(T::DbWeight::get().reads(33))
			.saturating_add(T::DbWeight::get().writes(25))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_partial() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810`
		//  Estimated: `4275`
		// Minimum execution time: 51_404_000 picoseconds.
		Weight::from_parts(53_499_000, 0)
			.saturating_add(Weight::from_parts(0, 4275))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:15 w:15)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11023`
		//  Estimated: `56563`
		// Minimum execution time: 475_487_000 picoseconds.
		Weight::from_parts(503_983_000, 0)
			.saturating_add(Weight::from_parts(0, 56563))
			.saturating_add(T::DbWeight::get().reads(39))
			.saturating_add(T::DbWeight::get().writes(30))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_future() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `431`
		//  Estimated: `3896`
		// Minimum execution time: 10_476_000 picoseconds.
		Weight::from_parts(12_223_000, 0)
			.saturating_add(Weight::from_parts(0, 3896))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:0)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	fn scheduler_paged_consume_preserve_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `662`
		//  Estimated: `4127`
		// Minimum execution time: 19_835_000 picoseconds.
		Weight::from_parts(21_512_000, 0)
			.saturating_add(Weight::from_parts(0, 4127))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	fn scheduler_paged_consume_delete_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `654`
		//  Estimated: `4119`
		// Minimum execution time: 21_371_000 picoseconds.
		Weight::from_parts(23_048_000, 0)
			.saturating_add(Weight::from_parts(0, 4119))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_tombstone_drain(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `584 + n * (8 ±0)`
		//  Estimated: `2903 + n * (2484 ±0)`
		// Minimum execution time: 19_207_000 picoseconds.
		Weight::from_parts(20_045_000, 0)
			.saturating_add(Weight::from_parts(0, 2903))
			// Standard Error: 836
			.saturating_add(Weight::from_parts(2_150_719, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 2484).saturating_mul(n.into()))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:5000)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_mixed_scan(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `789 + n * (86 ±0)`
		//  Estimated: `3092 + n * (2562 ±0)`
		// Minimum execution time: 22_349_000 picoseconds.
		Weight::from_parts(22_978_000, 0)
			.saturating_add(Weight::from_parts(0, 3092))
			// Standard Error: 30_037
			.saturating_add(Weight::from_parts(12_409_795, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2562).saturating_mul(n.into()))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:16 w:16)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:999 w:999)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `Measured`)
	/// Storage: `AAA::ActorProgram` (r:999 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `Measured`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `Measured`)
	/// Storage: `AAA::ActorFunding` (r:999 w:999)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// The range of component `n` is `[1, 1000]`.
	fn scheduler_paged_execute_cheap(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873 + n * (254 ±0)`
		//  Estimated: `4332 + n * (2730 ±0)`
		// Minimum execution time: 88_839_000 picoseconds.
		Weight::from_parts(89_468_000, 0)
			.saturating_add(Weight::from_parts(0, 4332))
			// Standard Error: 66_630
			.saturating_add(Weight::from_parts(64_353_651, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2730).saturating_mul(n.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `710`
		//  Estimated: `3521`
		// Minimum execution time: 13_131_000 picoseconds.
		Weight::from_parts(14_806_000, 0)
			.saturating_add(Weight::from_parts(0, 3521))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_notify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1344`
		//  Estimated: `12141`
		// Minimum execution time: 86_255_000 picoseconds.
		Weight::from_parts(90_585_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(961), added: 3436, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 10]`.
	fn funding_batch_promotion(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425 + a * (37 ±0)`
		//  Estimated: `4426`
		// Minimum execution time: 18_997_000 picoseconds.
		Weight::from_parts(18_749_402, 0)
			.saturating_add(Weight::from_parts(0, 4426))
			// Standard Error: 2_568
			.saturating_add(Weight::from_parts(2_400_885, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::IngressOverflowLen` (r:1 w:0)
	/// Proof: `AAA::IngressOverflowLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn compatibility_ingress_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `311`
		//  Estimated: `1489`
		// Minimum execution time: 5_587_000 picoseconds.
		Weight::from_parts(7_054_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::IngressOverflowHead` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowHead` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IngressOverflowLen` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IngressOverflowSlots` (r:1 w:1)
	/// Proof: `AAA::IngressOverflowSlots` (`max_values`: None, `max_size`: Some(83), added: 2558, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(8676), added: 11151, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn compatibility_ingress_drain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `914`
		//  Estimated: `12141`
		// Minimum execution time: 57_131_000 picoseconds.
		Weight::from_parts(59_855_000, 0)
			.saturating_add(Weight::from_parts(0, 12141))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}
