
//! Autogenerated weights for `pallet_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-19, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/llb/Repos/tmctol/template/target/release/wbuild/tmctol-runtime/tmctol_runtime.compact.compressed.wasm
// --pallet
// pallet_staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// /home/llb/Repos/tmctol/template/runtime/src/weights/pallet_staking.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_staking`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_staking::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn register_staking_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `229`
		//  Estimated: `6360`
		// Minimum execution time: 50_915_000 picoseconds.
		Weight::from_parts(52_522_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn initialize_staked_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `456`
		//  Estimated: `6220`
		// Minimum execution time: 48_750_000 picoseconds.
		Weight::from_parts(50_147_000, 0)
			.saturating_add(Weight::from_parts(0, 6220))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:1)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn convert_position_to_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `3675`
		// Minimum execution time: 61_391_000 picoseconds.
		Weight::from_parts(62_579_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn sync_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `417`
		//  Estimated: `3599`
		// Minimum execution time: 24_724_000 picoseconds.
		Weight::from_parts(26_191_000, 0)
			.saturating_add(Weight::from_parts(0, 3599))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `838`
		//  Estimated: `11699`
		// Minimum execution time: 106_300_000 picoseconds.
		Weight::from_parts(109_722_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1109`
		//  Estimated: `11699`
		// Minimum execution time: 118_802_000 picoseconds.
		Weight::from_parts(123_481_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn recover_unowned_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `832`
		//  Estimated: `6360`
		// Minimum execution time: 83_392_000 picoseconds.
		Weight::from_parts(89_189_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeBindings` (r:0 w:1)
	/// Proof: `Staking::NativeBindings` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn bind_native() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `2126`
		// Minimum execution time: 16_273_000 picoseconds.
		Weight::from_parts(17_670_000, 0)
			.saturating_add(Weight::from_parts(0, 2126))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::OperatorCommissions` (r:0 w:1)
	/// Proof: `Staking::OperatorCommissions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_operator_commission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_896_000 picoseconds.
		Weight::from_parts(12_013_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::NativeBindings` (r:0 w:1)
	/// Proof: `Staking::NativeBindings` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn clear_native_binding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_895_000 picoseconds.
		Weight::from_parts(11_943_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:1 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardActiveWeightSnapshots` (r:1 w:1)
	/// Proof: `Staking::RewardActiveWeightSnapshots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:1 w:0)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(83), added: 2558, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardActiveTotalWeights` (r:1 w:1)
	/// Proof: `Staking::RewardActiveTotalWeights` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:0 w:1)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	fn bootstrap_reward_snapshot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `714`
		//  Estimated: `3675`
		// Minimum execution time: 58_598_000 picoseconds.
		Weight::from_parts(61_740_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardTruncatedEpochs` (r:1 w:0)
	/// Proof: `Staking::RewardTruncatedEpochs` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardClaims` (r:1 w:1)
	/// Proof: `Staking::RewardClaims` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochAccruals` (r:1 w:0)
	/// Proof: `Staking::RewardEpochAccruals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:1 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:1 w:0)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardLiabilityBalances` (r:1 w:1)
	/// Proof: `Staking::RewardLiabilityBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1675`
		//  Estimated: `11699`
		// Minimum execution time: 153_723_000 picoseconds.
		Weight::from_parts(158_263_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardTruncatedEpochs` (r:16 w:0)
	/// Proof: `Staking::RewardTruncatedEpochs` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardClaims` (r:16 w:16)
	/// Proof: `Staking::RewardClaims` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochAccruals` (r:16 w:0)
	/// Proof: `Staking::RewardEpochAccruals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:16 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:16 w:0)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardLiabilityBalances` (r:1 w:1)
	/// Proof: `Staking::RewardLiabilityBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 16]`.
	fn claim_reward_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1470 + n * (215 ±0)`
		//  Estimated: `11699 + n * (2599 ±0)`
		// Minimum execution time: 153_513_000 picoseconds.
		Weight::from_parts(68_120_872, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			// Standard Error: 317_743
			.saturating_add(Weight::from_parts(100_710_933, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2599).saturating_mul(n.into()))
	}
}
