
//! Autogenerated weights for `pallet_deos_router`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/benchmarks/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_deos_router
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_deos_router.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_deos_router`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_deos_router::WeightInfo for SubstrateWeight<T> {
	/// Storage: `DeosRouter::RouterFee` (r:1 w:0)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SovereignIndex` (r:1 w:0)
	/// Proof: `Actors::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorIdentities` (r:1 w:0)
	/// Proof: `Actors::ActorIdentities` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorHot` (r:1 w:1)
	/// Proof: `Actors::ActorHot` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorContract` (r:1 w:0)
	/// Proof: `Actors::ActorContract` (`max_values`: None, `max_size`: Some(10533), added: 13008, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorFunding` (r:1 w:0)
	/// Proof: `Actors::ActorFunding` (`max_values`: None, `max_size`: Some(286), added: 2761, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ContinuationState` (r:1 w:0)
	/// Proof: `Actors::ContinuationState` (`max_values`: None, `max_size`: Some(689), added: 3164, mode: `MaxEncodedLen`)
	/// Storage: `Actors::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `Actors::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueHead` (r:1 w:0)
	/// Proof: `Actors::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueTail` (r:1 w:1)
	/// Proof: `Actors::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueOccupancy` (r:1 w:1)
	/// Proof: `Actors::QueueOccupancy` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueuePages` (r:1 w:1)
	/// Proof: `Actors::QueuePages` (`max_values`: None, `max_size`: Some(1050), added: 3525, mode: `MaxEncodedLen`)
	/// Storage: `Actors::NextQueueTicket` (r:1 w:1)
	/// Proof: `Actors::NextQueueTicket` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn direct_xyk_exact_input() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2988`
		//  Estimated: `13998`
		// Minimum execution time: 285_027_000 picoseconds.
		Weight::from_parts(302_068_000, 0)
			.saturating_add(Weight::from_parts(0, 13998))
			.saturating_add(T::DbWeight::get().reads(25))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `DeosRouter::RouterFee` (r:1 w:0)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:8 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SovereignIndex` (r:2 w:0)
	/// Proof: `Actors::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorIdentities` (r:2 w:0)
	/// Proof: `Actors::ActorIdentities` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorHot` (r:2 w:1)
	/// Proof: `Actors::ActorHot` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorContract` (r:2 w:0)
	/// Proof: `Actors::ActorContract` (`max_values`: None, `max_size`: Some(10533), added: 13008, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorFunding` (r:2 w:0)
	/// Proof: `Actors::ActorFunding` (`max_values`: None, `max_size`: Some(286), added: 2761, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ContinuationState` (r:1 w:0)
	/// Proof: `Actors::ContinuationState` (`max_values`: None, `max_size`: Some(689), added: 3164, mode: `MaxEncodedLen`)
	/// Storage: `Actors::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `Actors::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueHead` (r:1 w:0)
	/// Proof: `Actors::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueTail` (r:1 w:1)
	/// Proof: `Actors::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueOccupancy` (r:1 w:1)
	/// Proof: `Actors::QueueOccupancy` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueuePages` (r:1 w:1)
	/// Proof: `Actors::QueuePages` (`max_values`: None, `max_size`: Some(1050), added: 3525, mode: `MaxEncodedLen`)
	/// Storage: `Actors::NextQueueTicket` (r:1 w:1)
	/// Proof: `Actors::NextQueueTicket` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn direct_mint_exact_input() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3137`
		//  Estimated: `27006`
		// Minimum execution time: 298_786_000 picoseconds.
		Weight::from_parts(313_452_000, 0)
			.saturating_add(Weight::from_parts(0, 27006))
			.saturating_add(T::DbWeight::get().reads(32))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `DeosRouter::RouterFee` (r:1 w:0)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:7 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Feeds` (r:2 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:2 w:2)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SovereignIndex` (r:1 w:0)
	/// Proof: `Actors::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorIdentities` (r:1 w:0)
	/// Proof: `Actors::ActorIdentities` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorHot` (r:1 w:1)
	/// Proof: `Actors::ActorHot` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorContract` (r:1 w:0)
	/// Proof: `Actors::ActorContract` (`max_values`: None, `max_size`: Some(10533), added: 13008, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorFunding` (r:1 w:0)
	/// Proof: `Actors::ActorFunding` (`max_values`: None, `max_size`: Some(286), added: 2761, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ContinuationState` (r:1 w:0)
	/// Proof: `Actors::ContinuationState` (`max_values`: None, `max_size`: Some(689), added: 3164, mode: `MaxEncodedLen`)
	/// Storage: `Actors::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `Actors::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueHead` (r:1 w:0)
	/// Proof: `Actors::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueTail` (r:1 w:1)
	/// Proof: `Actors::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueueOccupancy` (r:1 w:1)
	/// Proof: `Actors::QueueOccupancy` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Actors::QueuePages` (r:1 w:1)
	/// Proof: `Actors::QueuePages` (`max_values`: None, `max_size`: Some(1050), added: 3525, mode: `MaxEncodedLen`)
	/// Storage: `Actors::NextQueueTicket` (r:1 w:1)
	/// Proof: `Actors::NextQueueTicket` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:2 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:2 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:2 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn native_anchored_exact_input() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3814`
		//  Estimated: `19253`
		// Minimum execution time: 415_353_000 picoseconds.
		Weight::from_parts(440_496_000, 0)
			.saturating_add(Weight::from_parts(0, 19253))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(17))
	}
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DeosRouter::RouterFee` (r:1 w:0)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:1 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn direct_xyk_exact_output() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1556`
		//  Estimated: `6208`
		// Minimum execution time: 158_892_000 picoseconds.
		Weight::from_parts(164_340_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:6 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DeosRouter::RouterFee` (r:1 w:0)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Feeds` (r:2 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:2 w:2)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:2 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationIngressRevisions` (r:2 w:0)
	/// Proof: `Actors::ObservationIngressRevisions` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:2 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn native_anchored_exact_output() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2374`
		//  Estimated: `16644`
		// Minimum execution time: 291_453_000 picoseconds.
		Weight::from_parts(304_233_000, 0)
			.saturating_add(Weight::from_parts(0, 16644))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `DeosRouter::RouterFee` (r:1 w:1)
	/// Proof: `DeosRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_router_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 6_984_000 picoseconds.
		Weight::from_parts(8_660_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
