
//! Autogenerated weights for `pallet_axial_router`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_axial_router
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_axial_router.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_axial_router`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_axial_router::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Feeds` (r:1 w:0)
	/// Proof: `Oracle::Feeds` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Observations` (r:1 w:1)
	/// Proof: `Oracle::Observations` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SovereignIndex` (r:1 w:0)
	/// Proof: `Actors::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorHot` (r:1 w:1)
	/// Proof: `Actors::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorProgram` (r:1 w:0)
	/// Proof: `Actors::ActorProgram` (`max_values`: None, `max_size`: Some(7144), added: 9619, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ActorFunding` (r:1 w:0)
	/// Proof: `Actors::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SystemQueueHead` (r:1 w:0)
	/// Proof: `Actors::SystemQueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SystemQueueTail` (r:1 w:1)
	/// Proof: `Actors::SystemQueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::UserQueueTail` (r:1 w:0)
	/// Proof: `Actors::UserQueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::UserQueueHead` (r:1 w:0)
	/// Proof: `Actors::UserQueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::NextQueueTicket` (r:1 w:1)
	/// Proof: `Actors::NextQueueTicket` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Actors::SystemQueuePages` (r:1 w:1)
	/// Proof: `Actors::SystemQueuePages` (`max_values`: None, `max_size`: Some(1050), added: 3525, mode: `MaxEncodedLen`)
	/// Storage: `Actors::ObservationSubscriberCount` (r:1 w:0)
	/// Proof: `Actors::ObservationSubscriberCount` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Actors::DirtyObservationFeeds` (r:1 w:0)
	/// Proof: `Actors::DirtyObservationFeeds` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2694`
		//  Estimated: `10609`
		// Minimum execution time: 314_289_000 picoseconds.
		Weight::from_parts(323_020_000, 0)
			.saturating_add(Weight::from_parts(0, 10609))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:1)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_router_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1489`
		// Minimum execution time: 9_428_000 picoseconds.
		Weight::from_parts(11_244_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
