
//! Autogenerated weights for `pallet_aaa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_aaa
// --extrinsic
// *
// --exclude-extrinsics
// pallet_aaa::process_remove_liquidity_indexed
// --exclude-extrinsics
// pallet_aaa::scheduler_on_idle_healthy_empty
// --exclude-extrinsics
// pallet_aaa::scheduler_cooldown_ineligible_idle
// --exclude-extrinsics
// pallet_aaa::scheduler_wakeup_sparse_gap_recovery
// --exclude-extrinsics
// pallet_aaa::close_aaa_system_pure
// --exclude-extrinsics
// pallet_aaa::condition_set_all_max
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress
// --exclude-extrinsics
// pallet_aaa::circular_chain_stress_100k
// --exclude-extrinsics
// pallet_aaa::circular_chain_100
// --exclude-extrinsics
// pallet_aaa::circular_chain_1000
// --exclude-extrinsics
// pallet_aaa::circular_chain_10000
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_aaa.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_aaa`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_aaa::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1920`
		//  Estimated: `9928`
		// Minimum execution time: 185_851_000 picoseconds.
		Weight::from_parts(190_879_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:2 w:2)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:2 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_user_aaa_at_slot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1846`
		//  Estimated: `9928`
		// Minimum execution time: 183_126_000 picoseconds.
		Weight::from_parts(188_784_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	fn create_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `947`
		//  Estimated: `3665`
		// Minimum execution time: 50_496_000 picoseconds.
		Weight::from_parts(53_359_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ClosedSystemAaaIds` (r:1 w:1)
	/// Proof: `AAA::ClosedSystemAaaIds` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:0)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:0)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	fn reopen_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `992`
		//  Estimated: `3665`
		// Minimum execution time: 56_083_000 picoseconds.
		Weight::from_parts(58_667_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn create_dormant_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `999`
		//  Estimated: `3665`
		// Minimum execution time: 42_045_000 picoseconds.
		Weight::from_parts(44_769_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::DormantAaaIdentities` (r:1 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:0)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:0 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	fn activate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `697`
		//  Estimated: `3665`
		// Minimum execution time: 43_163_000 picoseconds.
		Weight::from_parts(45_397_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:0 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::DormantAaaIdentities` (r:0 w:1)
	/// Proof: `AAA::DormantAaaIdentities` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn deactivate_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1246`
		//  Estimated: `9928`
		// Minimum execution time: 58_388_000 picoseconds.
		Weight::from_parts(60_554_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	fn pause_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `833`
		//  Estimated: `9928`
		// Minimum execution time: 33_734_000 picoseconds.
		Weight::from_parts(35_759_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	fn resume_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `838`
		//  Estimated: `9928`
		// Minimum execution time: 33_384_000 picoseconds.
		Weight::from_parts(35_690_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	fn manual_trigger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `9928`
		// Minimum execution time: 46_864_000 picoseconds.
		Weight::from_parts(49_378_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:1 w:1)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	fn close_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1899`
		//  Estimated: `9928`
		// Minimum execution time: 81_995_000 picoseconds.
		Weight::from_parts(84_998_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn update_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1346`
		//  Estimated: `9928`
		// Minimum execution time: 82_973_000 picoseconds.
		Weight::from_parts(88_211_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn update_funding_source_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1479`
		//  Estimated: `9928`
		// Minimum execution time: 90_096_000 picoseconds.
		Weight::from_parts(93_099_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:1)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn update_execution_plan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1849`
		//  Estimated: `9928`
		// Minimum execution time: 95_544_000 picoseconds.
		Weight::from_parts(98_687_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:0 w:1)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_global_circuit_breaker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_473_000 picoseconds.
		Weight::from_parts(9_080_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:0)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveActorLimit` (r:1 w:1)
	/// Proof: `AAA::ActiveActorLimit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_active_actor_limit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `1489`
		// Minimum execution time: 13_270_000 picoseconds.
		Weight::from_parts(15_086_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn permissionless_sweep() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1011`
		//  Estimated: `9928`
		// Minimum execution time: 30_521_000 picoseconds.
		Weight::from_parts(32_407_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `AAA::ActorHot` (r:5 w:5)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:5 w:5)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:5 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:5 w:5)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActiveAaaCount` (r:1 w:1)
	/// Proof: `AAA::ActiveAaaCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorIdentityCount` (r:1 w:1)
	/// Proof: `AAA::ActorIdentityCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:5 w:5)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlotMask` (r:5 w:5)
	/// Proof: `AAA::OwnerSlotMask` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:5 w:5)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 5]`.
	fn permissionless_sweep_many(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1006 + n * (442 ±0)`
		//  Estimated: `1489 + n * (8938 ±0)`
		// Minimum execution time: 73_963_000 picoseconds.
		Weight::from_parts(27_246_450, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			// Standard Error: 22_610
			.saturating_add(Weight::from_parts(49_837_449, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((7_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 8938).saturating_mul(n.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn fee_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1651`
		//  Estimated: `9928`
		// Minimum execution time: 108_605_000 picoseconds.
		Weight::from_parts(111_678_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn task_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1875`
		//  Estimated: `9928`
		// Minimum execution time: 156_377_000 picoseconds.
		Weight::from_parts(160_777_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3593`
		// Minimum execution time: 21_023_000 picoseconds.
		Weight::from_parts(22_908_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn task_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1410`
		//  Estimated: `9928`
		// Minimum execution time: 102_459_000 picoseconds.
		Weight::from_parts(106_440_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:3 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 4]`.
	fn condition_set_evaluation(c: u32, ) -> Weight {
		// Generated `Any(c)` regression is enveloped by the separate maximum `All(4)`
		// measurement. At c=4 the accepted maxima are 40_649_000 / 9_045 and seven reads.
		if c == 0 {
			return Weight::zero();
		}
		let bounded = u64::from(c.min(4));
		Weight::from_parts(12_524_232, 6_353)
			.saturating_add(Weight::from_parts(7_031_192, 673).saturating_mul(bounded))
			.saturating_add(T::DbWeight::get().reads(3u64.saturating_add(bounded)))
	}
	fn task_stop_cycle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_701_000 picoseconds.
		Weight::from_parts(5_238_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `AAA::SovereignIndex` (r:8 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:8 w:8)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:8 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:8 w:8)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:8 w:8)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[2, 8]`.
	fn task_split_transfer(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1229 + l * (448 ±0)`
		//  Estimated: `3675 + l * (8938 ±0)`
		// Minimum execution time: 267_706_000 picoseconds.
		Weight::from_parts(46_052_254, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			// Standard Error: 51_869
			.saturating_add(Weight::from_parts(116_533_005, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 8938).saturating_mul(l.into()))
	}
	/// Storage: `AssetRegistry::ForeignAssetMapping` (r:1 w:0)
	/// Proof: `AssetRegistry::ForeignAssetMapping` (`max_values`: None, `max_size`: Some(622), added: 3097, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn xcm_asset_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2073`
		//  Estimated: `9928`
		// Minimum execution time: 132_142_000 picoseconds.
		Weight::from_parts(137_590_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:1)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::NextPoolAssetId` (r:1 w:1)
	/// Proof: `AssetConversion::NextPoolAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::LpPairByTokenId` (r:1 w:1)
	/// Proof: `AxialRouter::LpPairByTokenId` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	fn task_add_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `805`
		//  Estimated: `11426`
		// Minimum execution time: 258_067_000 picoseconds.
		Weight::from_parts(266_239_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_donate_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1631`
		//  Estimated: `14035`
		// Minimum execution time: 201_496_000 picoseconds.
		Weight::from_parts(208_060_000, 0)
			.saturating_add(Weight::from_parts(0, 14035))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `AxialRouter::LpPairByTokenId` (r:1 w:0)
	/// Proof: `AxialRouter::LpPairByTokenId` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetConversion::Pools` (r:1 w:0)
	/// Proof: `AssetConversion::Pools` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn task_remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1463`
		//  Estimated: `8817`
		// Minimum execution time: 181_241_000 picoseconds.
		Weight::from_parts(186_689_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1252`
		//  Estimated: `11699`
		// Minimum execution time: 104_834_000 picoseconds.
		Weight::from_parts(108_465_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn task_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1594`
		//  Estimated: `11699`
		// Minimum execution time: 126_135_000 picoseconds.
		Weight::from_parts(129_977_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_in() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2422`
		//  Estimated: `9928`
		// Minimum execution time: 313_941_000 picoseconds.
		Weight::from_parts(328_120_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::RouterFee` (r:1 w:0)
	/// Proof: `AxialRouter::RouterFee` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:0)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	fn task_dex_exact_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2272`
		//  Estimated: `9928`
		// Minimum execution time: 307_376_000 picoseconds.
		Weight::from_parts(317_014_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::IdleStarvationState` (r:1 w:1)
	/// Proof: `AAA::IdleStarvationState` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	fn scheduler_on_idle_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `374`
		//  Estimated: `1493`
		// Minimum execution time: 13_619_000 picoseconds.
		Weight::from_parts(15_296_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	fn scheduler_actor_hot_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `533`
		//  Estimated: `3665`
		// Minimum execution time: 9_359_000 picoseconds.
		Weight::from_parts(10_966_000, 0)
			.saturating_add(Weight::from_parts(0, 3665))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn scheduler_actor_program_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `471`
		//  Estimated: `9928`
		// Minimum execution time: 16_203_000 picoseconds.
		Weight::from_parts(18_159_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_existing_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1724`
		//  Estimated: `5189`
		// Minimum execution time: 28_985_000 picoseconds.
		Weight::from_parts(31_010_000, 0)
			.saturating_add(Weight::from_parts(0, 5189))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_paged_append_new_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1210`
		//  Estimated: `4675`
		// Minimum execution time: 24_864_000 picoseconds.
		Weight::from_parts(27_029_000, 0)
			.saturating_add(Weight::from_parts(0, 4675))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	fn scheduler_wakeup_append_existing_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1410`
		//  Estimated: `4875`
		// Minimum execution time: 32_896_000 picoseconds.
		Weight::from_parts(35_270_000, 0)
			.saturating_add(Weight::from_parts(0, 4875))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	fn scheduler_wakeup_append_new_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1453`
		//  Estimated: `4918`
		// Minimum execution time: 35_200_000 picoseconds.
		Weight::from_parts(37_924_000, 0)
			.saturating_add(Weight::from_parts(0, 4918))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:2 w:2)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_replace_exact() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `770`
		//  Estimated: `6710`
		// Minimum execution time: 58_598_000 picoseconds.
		Weight::from_parts(61_043_000, 0)
			.saturating_add(Weight::from_parts(0, 6710))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:3 w:3)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	fn scheduler_wakeup_invalidate_middle_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1780`
		//  Estimated: `10195`
		// Minimum execution time: 44_769_000 picoseconds.
		Weight::from_parts(49_169_000, 0)
			.saturating_add(Weight::from_parts(0, 10195))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:16 w:16)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	fn scheduler_wakeup_drain_partial_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4010`
		//  Estimated: `44600`
		// Minimum execution time: 133_120_000 picoseconds.
		Weight::from_parts(142_269_000, 0)
			.saturating_add(Weight::from_parts(0, 44600))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(18))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:32 w:32)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_full_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6411`
		//  Estimated: `86601`
		// Minimum execution time: 247_522_000 picoseconds.
		Weight::from_parts(258_905_000, 0)
			.saturating_add(Weight::from_parts(0, 86601))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(36))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:2 w:2)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:33 w:33)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_dense_boundary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6654`
		//  Estimated: `89319`
		// Minimum execution time: 262_887_000 picoseconds.
		Weight::from_parts(277_763_000, 0)
			.saturating_add(Weight::from_parts(0, 89319))
			.saturating_add(T::DbWeight::get().reads(38))
			.saturating_add(T::DbWeight::get().writes(38))
	}
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:32 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_drain_stale_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5899`
		//  Estimated: `86089`
		// Minimum execution time: 157_425_000 picoseconds.
		Weight::from_parts(166_016_000, 0)
			.saturating_add(Weight::from_parts(0, 86089))
			.saturating_add(T::DbWeight::get().reads(36))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::WakeupBuckets` (r:14 w:14)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:10 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_insert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6167`
		//  Estimated: `41807`
		// Minimum execution time: 318_132_000 picoseconds.
		Weight::from_parts(337_269_000, 0)
			.saturating_add(Weight::from_parts(0, 41807))
			.saturating_add(T::DbWeight::get().reads(25))
			.saturating_add(T::DbWeight::get().writes(25))
	}
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:15 w:15)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	fn scheduler_wakeup_cursor_pop_min() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10659`
		//  Estimated: `56199`
		// Minimum execution time: 429_880_000 picoseconds.
		Weight::from_parts(460_192_000, 0)
			.saturating_add(Weight::from_parts(0, 56199))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(26))
	}
	/// Storage: `AAA::WakeupBuckets` (r:14 w:14)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_remove_exact() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10227`
		//  Estimated: `55767`
		// Minimum execution time: 404_946_000 picoseconds.
		Weight::from_parts(430_299_000, 0)
			.saturating_add(Weight::from_parts(0, 55767))
			.saturating_add(T::DbWeight::get().reads(33))
			.saturating_add(T::DbWeight::get().writes(25))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_partial() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `818`
		//  Estimated: `4283`
		// Minimum execution time: 50_846_000 picoseconds.
		Weight::from_parts(53_359_000, 0)
			.saturating_add(Weight::from_parts(0, 4283))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:18 w:10)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::WakeupBuckets` (r:15 w:15)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `Measured`)
	/// Storage: `AAA::WakeupPages` (r:1 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11031`
		//  Estimated: `56571`
		// Minimum execution time: 472_763_000 picoseconds.
		Weight::from_parts(503_563_000, 0)
			.saturating_add(Weight::from_parts(0, 56571))
			.saturating_add(T::DbWeight::get().reads(39))
			.saturating_add(T::DbWeight::get().writes(30))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `Measured`)
	fn scheduler_wakeup_cursor_worker_future() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `431`
		//  Estimated: `3896`
		// Minimum execution time: 10_477_000 picoseconds.
		Weight::from_parts(12_083_000, 0)
			.saturating_add(Weight::from_parts(0, 3896))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:0)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	fn scheduler_paged_consume_preserve_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `670`
		//  Estimated: `4135`
		// Minimum execution time: 19_556_000 picoseconds.
		Weight::from_parts(21_372_000, 0)
			.saturating_add(Weight::from_parts(0, 4135))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	fn scheduler_paged_consume_delete_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `662`
		//  Estimated: `4127`
		// Minimum execution time: 20_952_000 picoseconds.
		Weight::from_parts(22_838_000, 0)
			.saturating_add(Weight::from_parts(0, 4127))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:0)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_tombstone_drain(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `584 + n * (8 ±0)`
		//  Estimated: `2903 + n * (2484 ±0)`
		// Minimum execution time: 18_718_000 picoseconds.
		Weight::from_parts(19_696_000, 0)
			.saturating_add(Weight::from_parts(0, 2903))
			// Standard Error: 2_914
			.saturating_add(Weight::from_parts(2_214_430, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 2484).saturating_mul(n.into()))
	}
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:157 w:157)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:10000 w:5000)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// The range of component `n` is `[1, 10000]`.
	fn scheduler_paged_mixed_scan(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `789 + n * (90 ±0)`
		//  Estimated: `3089 + n * (2566 ±0)`
		// Minimum execution time: 21_931_000 picoseconds.
		Weight::from_parts(22_979_000, 0)
			.saturating_add(Weight::from_parts(0, 3089))
			// Standard Error: 20_228
			.saturating_add(Weight::from_parts(12_634_085, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2566).saturating_mul(n.into()))
	}
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:0)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `Measured`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::ActorHot` (r:1007 w:999)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::QueueHead` (r:1 w:1)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `AAA::QueuePages` (r:16 w:16)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `Measured`)
	/// Storage: `AAA::ActorProgram` (r:999 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `Measured`)
	/// Storage: `AAA::GlobalCircuitBreaker` (r:1 w:0)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `Measured`)
	/// The range of component `n` is `[1, 1000]`.
	fn scheduler_paged_execute_cheap(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `999 + n * (231 ±0)`
		//  Estimated: `21773 + n * (2707 ±0)`
		// Minimum execution time: 95_265_000 picoseconds.
		Weight::from_parts(98_059_000, 0)
			.saturating_add(Weight::from_parts(0, 21773))
			// Standard Error: 51_765
			.saturating_add(Weight::from_parts(52_124_345, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2707).saturating_mul(n.into()))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `Measured`)
	/// Storage: `AAA::ContinuationState` (r:0 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `Measured`)
	/// The range of component `s` is `[0, 20]`.
	fn continuation_suspend(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `4180`
		// Minimum execution time: 26_610_000 picoseconds.
		Weight::from_parts(28_944_390, 0)
			.saturating_add(Weight::from_parts(0, 4180))
			// Standard Error: 645
			.saturating_add(Weight::from_parts(39_639, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `Measured`)
	fn continuation_retry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `801`
		//  Estimated: `4266`
		// Minimum execution time: 19_905_000 picoseconds.
		Weight::from_parts(21_930_000, 0)
			.saturating_add(Weight::from_parts(0, 4266))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `Measured`)
	/// Storage: `AAA::ContinuationState` (r:0 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `Measured`)
	fn continuation_complete() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `565`
		//  Estimated: `4030`
		// Minimum execution time: 16_552_000 picoseconds.
		Weight::from_parts(18_299_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ContinuationState` (r:1 w:1)
	/// Proof: `AAA::ContinuationState` (`max_values`: None, `max_size`: Some(497), added: 2972, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:1)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueuePages` (r:1 w:1)
	/// Proof: `AAA::QueuePages` (`max_values`: None, `max_size`: Some(538), added: 3013, mode: `MaxEncodedLen`)
	fn continuation_cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1228`
		//  Estimated: `9928`
		// Minimum execution time: 55_525_000 picoseconds.
		Weight::from_parts(58_668_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// The range of component `n` is `[1, 10]`.
	fn continuation_suffix_admission(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 419_000 picoseconds.
		Weight::from_parts(1_434_192, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 115
			.saturating_add(Weight::from_parts(2_928, 0).saturating_mul(n.into()))
	}
	/// Storage: `AAA::SovereignIndex` (r:2 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `710`
		//  Estimated: `6052`
		// Minimum execution time: 13_340_000 picoseconds.
		Weight::from_parts(15_156_000, 0)
			.saturating_add(Weight::from_parts(0, 6052))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `AAA::SovereignIndex` (r:1 w:0)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorProgram` (r:1 w:0)
	/// Proof: `AAA::ActorProgram` (`max_values`: None, `max_size`: Some(6463), added: 8938, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueHead` (r:1 w:0)
	/// Proof: `AAA::QueueHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::QueueTail` (r:1 w:0)
	/// Proof: `AAA::QueueTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupBuckets` (r:1 w:1)
	/// Proof: `AAA::WakeupBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorLen` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorLen` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupCursorPages` (r:1 w:1)
	/// Proof: `AAA::WakeupCursorPages` (`max_values`: None, `max_size`: Some(153), added: 2628, mode: `MaxEncodedLen`)
	/// Storage: `AAA::WakeupPages` (r:0 w:1)
	/// Proof: `AAA::WakeupPages` (`max_values`: None, `max_size`: Some(343), added: 2818, mode: `MaxEncodedLen`)
	fn transaction_extension_ingress_notify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1435`
		//  Estimated: `9928`
		// Minimum execution time: 88_211_000 picoseconds.
		Weight::from_parts(91_563_000, 0)
			.saturating_add(Weight::from_parts(0, 9928))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::ActorFunding` (r:1 w:1)
	/// Proof: `AAA::ActorFunding` (`max_values`: None, `max_size`: Some(960), added: 3435, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ActorHot` (r:1 w:1)
	/// Proof: `AAA::ActorHot` (`max_values`: None, `max_size`: Some(200), added: 2675, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 10]`.
	fn funding_batch_promotion(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739 + a * (37 ±0)`
		//  Estimated: `4425`
		// Minimum execution time: 25_003_000 picoseconds.
		Weight::from_parts(25_482_826, 0)
			.saturating_add(Weight::from_parts(0, 4425))
			// Standard Error: 4_436
			.saturating_add(Weight::from_parts(2_339_654, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
