
//! Autogenerated weights for `pallet_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// template/target/benchmarks/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_governance
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// template/runtime/src/weights/pallet_governance.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_governance`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_governance::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Governance::WinningVoteResolutionWindows` (r:1 w:1)
	/// Proof: `Governance::WinningVoteResolutionWindows` (`max_values`: None, `max_size`: Some(799), added: 3274, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ParticipationTotalsByAccount` (r:1 w:1)
	/// Proof: `Governance::ParticipationTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:1 w:1)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	fn record_winning_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `40351`
		// Minimum execution time: 27_099_000 picoseconds.
		Weight::from_parts(29_124_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Governance::WinningVoteResolutionWindows` (r:1 w:1)
	/// Proof: `Governance::WinningVoteResolutionWindows` (`max_values`: None, `max_size`: Some(799), added: 3274, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ParticipationTotalsByAccount` (r:256 w:256)
	/// Proof: `Governance::ParticipationTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:256 w:256)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 256]`.
	fn record_winning_vote_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `40351 + n * (2603 ±0)`
		// Minimum execution time: 28_566_000 picoseconds.
		Weight::from_parts(29_543_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			// Standard Error: 18_183
			.saturating_add(Weight::from_parts(16_277_412, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:126 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMaturityBuckets` (r:1 w:1)
	/// Proof: `Governance::ProposalMaturityBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorshipTotalsByAccount` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorshipTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8582`
		//  Estimated: `321912`
		// Minimum execution time: 528_568_000 picoseconds.
		Weight::from_parts(549_869_000, 0)
			.saturating_add(Weight::from_parts(0, 321912))
			.saturating_add(T::DbWeight::get().reads(130))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Governance::VotePowerCustodyByAccount` (r:1 w:0)
	/// Proof: `Governance::VotePowerCustodyByAccount` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::StatusFor` (r:1 w:0)
	/// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::RequestStatusFor` (r:1 w:0)
	/// Proof: `Preimage::RequestStatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::PreimageFor` (r:1 w:0)
	/// Proof: `Preimage::PreimageFor` (`max_values`: None, `max_size`: Some(4194344), added: 4196819, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:127 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMaturityBuckets` (r:1 w:1)
	/// Proof: `Governance::ProposalMaturityBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorshipTotalsByAccount` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorshipTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn submit_signed_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9501`
		//  Estimated: `4197809`
		// Minimum execution time: 607_000_000 picoseconds.
		Weight::from_parts(630_049_000, 0)
			.saturating_add(Weight::from_parts(0, 4197809))
			.saturating_add(T::DbWeight::get().reads(138))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:1 w:1)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:1 w:0)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalVotesByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Governance::VotePowerCustodyByAccount` (r:1 w:1)
	/// Proof: `Governance::VotePowerCustodyByAccount` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::GovernanceLocks` (r:1 w:1)
	/// Proof: `Governance::GovernanceLocks` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ParticipationTotalsByAccount` (r:256 w:256)
	/// Proof: `Governance::ParticipationTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:1 w:0)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `22412`
		//  Estimated: `656094`
		// Minimum execution time: 1_203_594_000 picoseconds.
		Weight::from_parts(1_249_760_000, 0)
			.saturating_add(Weight::from_parts(0, 656094))
			.saturating_add(T::DbWeight::get().reads(269))
			.saturating_add(T::DbWeight::get().writes(271))
	}
	/// Storage: `Governance::VotePowerCustodyByAccount` (r:1 w:1)
	/// Proof: `Governance::VotePowerCustodyByAccount` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn unlock_vote_power() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `855`
		//  Estimated: `6208`
		// Minimum execution time: 65_302_000 picoseconds.
		Weight::from_parts(67_817_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Governance::ProposalVotesByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteResolutionWindows` (r:1 w:1)
	/// Proof: `Governance::WinningVoteResolutionWindows` (`max_values`: None, `max_size`: Some(799), added: 3274, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ParticipationTotalsByAccount` (r:256 w:256)
	/// Proof: `Governance::ParticipationTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:256 w:256)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:1 w:1)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorshipTotalsByAccount` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorshipTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PendingEnactmentBuckets` (r:1 w:1)
	/// Proof: `Governance::PendingEnactmentBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 256]`.
	fn resolve_proposal(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `96703 + n * (2603 ±0)`
		// Minimum execution time: 78_084_000 picoseconds.
		Weight::from_parts(78_643_000, 0)
			.saturating_add(Weight::from_parts(0, 96703))
			// Standard Error: 19_347
			.saturating_add(Weight::from_parts(16_543_654, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(14))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:1 w:1)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalVotesByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:1 w:0)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 256]`.
	fn resolve_proposal_from_votes(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `815 + n * (104 ±0)`
		//  Estimated: `96703`
		// Minimum execution time: 102_598_000 picoseconds.
		Weight::from_parts(106_671_658, 0)
			.saturating_add(Weight::from_parts(0, 96703))
			// Standard Error: 1_187
			.saturating_add(Weight::from_parts(1_037_471, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalVotesByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn reject_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `321`
		//  Estimated: `11679`
		// Minimum execution time: 37_296_000 picoseconds.
		Weight::from_parts(39_600_000, 0)
			.saturating_add(Weight::from_parts(0, 11679))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:1)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:1 w:1)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalVotesByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:1 w:0)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:1 w:1)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:0 w:1)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 256]`.
	fn force_resolve_proposal_from_votes(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `815 + n * (104 ±0)`
		//  Estimated: `96703`
		// Minimum execution time: 91_982_000 picoseconds.
		Weight::from_parts(94_216_612, 0)
			.saturating_add(Weight::from_parts(0, 96703))
			// Standard Error: 689
			.saturating_add(Weight::from_parts(1_004_803, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Governance::ActiveProposals` (r:1 w:0)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMaturityBuckets` (r:1 w:1)
	/// Proof: `Governance::ProposalMaturityBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn requeue_proposal_for_auto_finalization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `3518`
		// Minimum execution time: 15_994_000 picoseconds.
		Weight::from_parts(17_810_000, 0)
			.saturating_add(Weight::from_parts(0, 3518))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Governance::LastProcessedEpoch` (r:1 w:1)
	/// Proof: `Governance::LastProcessedEpoch` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Governance::CurrentEpochServicePhase` (r:1 w:0)
	/// Proof: `Governance::CurrentEpochServicePhase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMaturityBuckets` (r:1 w:0)
	/// Proof: `Governance::ProposalMaturityBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PendingEnactmentBuckets` (r:1 w:0)
	/// Proof: `Governance::PendingEnactmentBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:0)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:0)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	fn service_epoch_catch_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `40351`
		// Minimum execution time: 12_362_000 picoseconds.
		Weight::from_parts(14_109_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Governance::ProposalMaturityBuckets` (r:1 w:1)
	/// Proof: `Governance::ProposalMaturityBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposals` (r:3 w:3)
	/// Proof: `Governance::ActiveProposals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:3 w:3)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalVotesByItem` (r:3 w:3)
	/// Proof: `Governance::ProposalVotesByItem` (`max_values`: None, `max_size`: Some(93238), added: 95713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:3 w:0)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalConfirmStartedAt` (r:3 w:3)
	/// Proof: `Governance::ProposalConfirmStartedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteResolutionWindows` (r:1 w:1)
	/// Proof: `Governance::WinningVoteResolutionWindows` (`max_values`: None, `max_size`: Some(799), added: 3274, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ParticipationTotalsByAccount` (r:768 w:768)
	/// Proof: `Governance::ParticipationTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:768 w:768)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorsByItem` (r:3 w:3)
	/// Proof: `Governance::ProposalAuthorsByItem` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ActiveProposalIdsByDomain` (r:1 w:1)
	/// Proof: `Governance::ActiveProposalIdsByDomain` (`max_values`: None, `max_size`: Some(534), added: 3009, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalAuthorshipTotalsByAccount` (r:3 w:3)
	/// Proof: `Governance::ProposalAuthorshipTotalsByAccount` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::PendingEnactmentBuckets` (r:1 w:1)
	/// Proof: `Governance::PendingEnactmentBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:3)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:3)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:3)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 3]`.
	fn service_maturing_proposals(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699 + n * (13521 ±0)`
		//  Estimated: `40351 + n * (666368 ±0)`
		// Minimum execution time: 4_175_948_000 picoseconds.
		Weight::from_parts(4_256_477_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			// Standard Error: 56_476_929
			.saturating_add(Weight::from_parts(2_500_144_905, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().reads((519_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((521_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 666368).saturating_mul(n.into()))
	}
	/// Storage: `Governance::PendingEnactmentBuckets` (r:2 w:2)
	/// Proof: `Governance::PendingEnactmentBuckets` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:4 w:0)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:4 w:0)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:4 w:0)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 4]`.
	fn service_pending_enactments(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193 + n * (77 ±0)`
		//  Estimated: `6046 + n * (2634 ±0)`
		// Minimum execution time: 18_019_000 picoseconds.
		Weight::from_parts(6_733_859, 0)
			.saturating_add(Weight::from_parts(0, 6046))
			// Standard Error: 3_484
			.saturating_add(Weight::from_parts(13_019_956, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 2634).saturating_mul(n.into()))
	}
	/// Storage: `Governance::FinalizedProposalOutcomeExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::FinalizedProposalOutcomeExpiryBuckets` (`max_values`: None, `max_size`: Some(8214), added: 10689, mode: `MaxEncodedLen`)
	/// Storage: `Governance::FinalizedProposals` (r:0 w:1023)
	/// Proof: `Governance::FinalizedProposals` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalPendingEnactmentAt` (r:0 w:1023)
	/// Proof: `Governance::ProposalPendingEnactmentAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalMetadataByItem` (r:0 w:1023)
	/// Proof: `Governance::ProposalMetadataByItem` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalWinningPrimaryOptionByItem` (r:0 w:1023)
	/// Proof: `Governance::ProposalWinningPrimaryOptionByItem` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Governance::ProposalUrgentAuthorizedAt` (r:0 w:1023)
	/// Proof: `Governance::ProposalUrgentAuthorizedAt` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1024]`.
	fn service_finalized_proposal_outcomes(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183 + n * (8 ±0)`
		//  Estimated: `11679`
		// Minimum execution time: 15_156_000 picoseconds.
		Weight::from_parts(15_366_000, 0)
			.saturating_add(Weight::from_parts(0, 11679))
			// Standard Error: 7_127
			.saturating_add(Weight::from_parts(8_206_051, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((5_u64).saturating_mul(n.into())))
	}
	/// Storage: `Governance::ExpiryBuckets` (r:1 w:1)
	/// Proof: `Governance::ExpiryBuckets` (`max_values`: None, `max_size`: Some(36886), added: 39361, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:512 w:512)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 512]`.
	fn service_expiring_accounts(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `165 + n * (106 ±0)`
		//  Estimated: `40351 + n * (2603 ±0)`
		// Minimum execution time: 15_784_000 picoseconds.
		Weight::from_parts(16_413_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			// Standard Error: 3_660
			.saturating_add(Weight::from_parts(7_035_354, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
	}
}
