
//! Autogenerated weights for `pallet_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/llb/Repos/deos/template/target/release/wbuild/deos-runtime/deos_runtime.compact.compressed.wasm
// --pallet
// pallet_staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// /home/llb/Repos/deos/template/runtime/src/weights/pallet_staking.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_staking`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_staking::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::LiveStakedAssetBaseAssets` (r:1 w:1)
	/// Proof: `Staking::LiveStakedAssetBaseAssets` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardAssetsByGovernanceDomain` (r:1 w:1)
	/// Proof: `Staking::RewardAssetsByGovernanceDomain` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn register_staking_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `6360`
		// Minimum execution time: 69_563_000 picoseconds.
		Weight::from_parts(73_753_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Staking::LiveStakedAssetBaseAssets` (r:1 w:1)
	/// Proof: `Staking::LiveStakedAssetBaseAssets` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn initialize_staked_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `487`
		//  Estimated: `6220`
		// Minimum execution time: 58_248_000 picoseconds.
		Weight::from_parts(62_998_000, 0)
			.saturating_add(Weight::from_parts(0, 6220))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:1)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn convert_position_to_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810`
		//  Estimated: `3675`
		// Minimum execution time: 62_020_000 picoseconds.
		Weight::from_parts(63_906_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn sync_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492`
		//  Estimated: `3599`
		// Minimum execution time: 27_588_000 picoseconds.
		Weight::from_parts(33_315_000, 0)
			.saturating_add(Weight::from_parts(0, 3599))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1044`
		//  Estimated: `11699`
		// Minimum execution time: 113_424_000 picoseconds.
		Weight::from_parts(129_278_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1245`
		//  Estimated: `11699`
		// Minimum execution time: 122_085_000 picoseconds.
		Weight::from_parts(138_149_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn recover_unowned_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1011`
		//  Estimated: `6360`
		// Minimum execution time: 90_726_000 picoseconds.
		Weight::from_parts(100_643_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
	/// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeDelegationCacheDirty` (r:1 w:0)
	/// Proof: `Staking::NativeDelegationCacheDirty` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CachedNativeDelegations` (r:1 w:1)
	/// Proof: `Staking::CachedNativeDelegations` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CachedOperatorNativeShares` (r:1 w:1)
	/// Proof: `Staking::CachedOperatorNativeShares` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeBindings` (r:0 w:1)
	/// Proof: `Staking::NativeBindings` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn bind_native() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `854`
		//  Estimated: `3675`
		// Minimum execution time: 50_077_000 picoseconds.
		Weight::from_parts(61_112_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::OperatorCommissions` (r:0 w:1)
	/// Proof: `Staking::OperatorCommissions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_operator_commission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_406_000 picoseconds.
		Weight::from_parts(12_921_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::NativeDelegationCacheDirty` (r:1 w:0)
	/// Proof: `Staking::NativeDelegationCacheDirty` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CachedNativeDelegations` (r:1 w:1)
	/// Proof: `Staking::CachedNativeDelegations` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Staking::NativeBindings` (r:0 w:1)
	/// Proof: `Staking::NativeBindings` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn clear_native_binding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `3561`
		// Minimum execution time: 20_464_000 picoseconds.
		Weight::from_parts(26_190_000, 0)
			.saturating_add(Weight::from_parts(0, 3561))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Staking::Pools` (r:1 w:0)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:1 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardActiveWeightSnapshots` (r:1 w:1)
	/// Proof: `Staking::RewardActiveWeightSnapshots` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Positions` (r:1 w:0)
	/// Proof: `Staking::Positions` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Governance::WinningVoteWindows` (r:1 w:0)
	/// Proof: `Governance::WinningVoteWindows` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardActiveTotalWeights` (r:1 w:1)
	/// Proof: `Staking::RewardActiveTotalWeights` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:0 w:1)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	fn bootstrap_reward_snapshot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `860`
		//  Estimated: `3675`
		// Minimum execution time: 61_602_000 picoseconds.
		Weight::from_parts(64_394_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardTruncatedEpochs` (r:1 w:0)
	/// Proof: `Staking::RewardTruncatedEpochs` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardClaims` (r:1 w:1)
	/// Proof: `Staking::RewardClaims` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochAccruals` (r:1 w:0)
	/// Proof: `Staking::RewardEpochAccruals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:1 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:1 w:0)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardLiabilityBalances` (r:1 w:1)
	/// Proof: `Staking::RewardLiabilityBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1778`
		//  Estimated: `11699`
		// Minimum execution time: 156_448_000 picoseconds.
		Weight::from_parts(175_445_000, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `Staking::Pools` (r:1 w:1)
	/// Proof: `Staking::Pools` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardTruncatedEpochs` (r:16 w:0)
	/// Proof: `Staking::RewardTruncatedEpochs` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardClaims` (r:16 w:16)
	/// Proof: `Staking::RewardClaims` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochAccruals` (r:16 w:0)
	/// Proof: `Staking::RewardEpochAccruals` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTotalWeights` (r:16 w:0)
	/// Proof: `Staking::RewardEpochTotalWeights` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochWeightSnapshots` (r:16 w:0)
	/// Proof: `Staking::RewardEpochWeightSnapshots` (`max_values`: None, `max_size`: Some(124), added: 2599, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardLiabilityBalances` (r:1 w:1)
	/// Proof: `Staking::RewardLiabilityBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Staking::RewardEpochTouchedAccounts` (r:1 w:1)
	/// Proof: `Staking::RewardEpochTouchedAccounts` (`max_values`: None, `max_size`: Some(8234), added: 10709, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 16]`.
	fn claim_reward_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1573 + n * (215 ±0)`
		//  Estimated: `11699 + n * (2599 ±0)`
		// Minimum execution time: 154_561_000 picoseconds.
		Weight::from_parts(64_461_168, 0)
			.saturating_add(Weight::from_parts(0, 11699))
			// Standard Error: 435_862
			.saturating_add(Weight::from_parts(101_895_959, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2599).saturating_mul(n.into()))
	}
}
